version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/wedding-planner-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "uv"
    directory: "/wedding-planner-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
