import { createContext, useContext, useState, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import api from '../lib/api'

const LanguageContext = createContext()

const translations = {
  en: {
    welcome: 'Welcome',
    rsvp: 'RSVP',
    hi: 'Hi',
    fillForm: 'Please fill out the form below',
    introduction: "We are absolutely thrilled to celebrate this special day with you! Your presence means the world to us, and we can't wait to share this beautiful moment together. Please take a moment to fill out the form below so we can make sure everything is perfect for your visit. We've included sections for dietary preferences, music requests, and any special accommodations you might need. Don't hesitate to reach out if you have any questions. We're looking forward to seeing you soon!",
    rsvpDetails: 'RSVP Details',
    overnightStay: 'Overnight Stay',
    overnightStayQuestion: 'Would you like to stay overnight?',
    overnightStayYes: 'Yes, I would like to stay overnight',
    overnightStayNo: 'No, I would not like to stay overnight',
    overnightStayNote: 'You need to arrange accommodation yourselves.',
    select: 'Select...',
    numberOfGuests: 'Number of Guests',
    rsvpStatus: 'RSVP Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    declined: 'Declined',
    contactInfo: 'Contact Information',
    phone: 'Phone',
    address: 'Address',
    musicWish: 'Music Wish',
    songRequests: 'Song Requests',
    musicPlaceholder: 'What songs would you like to hear at the wedding?',
    dietaryInfo: 'Dietary Information',
    dietaryRestrictions: 'Dietary Restrictions',
    dietaryPlaceholder: 'e.g., Vegetarian, Vegan, Gluten-free',
    allergies: 'Allergies',
    allergiesPlaceholder: 'Please list any food allergies',
    specialRequests: 'Special Requests',
    specialPlaceholder: 'Any special requests or additional information',
    submitRSVP: 'Submit RSVP',
    saving: 'Saving...',
    ourStory: 'Our Story',
    invalidLink: 'Invalid RSVP Link',
    invalidLinkMessage: 'This RSVP link is not valid. Please check the link and try again.',
    loadingRSVP: 'Loading your RSVP...',
    confirmAttendance: 'Please confirm your attendance',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Your Wedding Pass',
    yourInvitation: 'Your Invitation',
    joinOurCelebration: 'Join Our Celebration',
    passIntro: 'A little wedding companion you can return to anytime.',
    loadingWeddingPass: 'Loading your Wedding Pass...',
    invalidInvitationLinkTitle: 'Invalid Invitation Link',
    invalidInvitationLinkMessage: 'This invitation link is not valid. Please check the link and try again.',
    authFailed: 'Failed to authenticate',
    authMissing: 'No authentication token available',
    saveFailed: 'Could not save your answer. Please try again.',
    stepLabel: 'Step',
    statusPending: 'Not decided yet',
    statusYes: 'Coming',
    statusNo: 'Not coming',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    next: 'Next',
    continue: 'Continue',
    skipForNow: 'Skip for now',
    youCanEditAnytime: 'You can change your answers later.',
    ourBigDay: 'our big day',
    qCelebrateOnDate: 'Will you celebrate our wedding with us on {{date}}?',
    qCelebrateSub: 'Just one tap — we’ll take care of the rest.',
    qBothComing: 'Will both of you be joining?',
    qBothComingSub: 'So we can plan the seats and the menu.',
    bothOfUs: 'Yes, both of us',
    justMe: 'Just me',
    qGroupHowMany: 'How many of you will be coming?',
    qGroupHowManySub: 'Up to {{max}} invited — what should we plan for?',
    groupMaxNote: 'Max invited: {{max}}',
    people: 'people',
    qOvernight: 'Will you stay overnight?',
    qOvernightSub: 'This helps us plan the sleeping arrangements.',
    overnightNoteSoft: 'Accommodation is organized individually.',
    qDietary: 'Any dietary restrictions?',
    qDietarySub: 'One short note is perfect.',
    dietaryPlaceholderShort: 'e.g. vegetarian, gluten-free, no nuts…',
    qNotes: 'Anything else you’d like us to know?',
    qNotesSub: 'Optional — share what matters to you.',
    notesPlaceholder: 'Optional note…',
    qAddPhoto: 'Want to add a photo?',
    qAddPhotoSub: 'Optional — it’ll appear in the guest gallery after approval.',
    photoOptional: 'Totally optional. You can also do this later.',
    photoCaptionPlaceholder: 'Caption (optional)',
    uploadAndContinue: 'Upload & continue',
    photoUploaded: 'Photo uploaded (awaiting approval).',
    photoUploadFailed: 'Photo upload failed. Please try again.',
    doneTitle: 'You’re all set',
    doneSub: 'Thanks — your Wedding Pass is saved.',
    doneYesTitle: 'We’re so happy you’re joining us',
    doneYesSub: 'Your Wedding Pass is saved — see you soon.',
    doneNoTitle: 'Thank you for letting us know',
    doneNoSub: 'Your Wedding Pass is saved. You can still check details below.',
    addToCalendar: 'Add to calendar',
    calendarNotConfigured: 'Calendar export is not configured yet (missing wedding_date_iso).',
    calendarEventTitle: 'Wedding Celebration',
    calendarEventDescription: 'Our big day — details in your Wedding Pass.',
    saveThisPageTitle: 'Tip:',
    saveThisPageBody: 'Bookmark this page so you can come back anytime.',
    whyReturnTitle: 'Why return?',
    whyReturnBody: 'We’ll keep updating this page with everything you need for the day.',
    openFullInfo: 'Open full info page',
    editAnswers: 'Update my answers',
    tabNeedToKnow: 'All you need to know',
    tabVenue: 'Wedding venue',
    tabDayItself: 'The day itself',
    tabYourEvening: 'Your evening',
    comingSoon: 'Coming soon',
    needToKnowTitle: 'All you need to know',
    needToKnowBody: 'Location, travel tips, gifts and dress code will live here.',
    giftDressCodeTitle: 'Gifts & dress code',
    giftDressCodeBody: 'We’ll share the details here as we get closer to the date.',
    dayItselfTitle: 'Timeline',
  },
  de: {
    welcome: 'Willkommen',
    rsvp: 'RSVP',
    hi: 'Hallo',
    fillForm: 'Bitte fülle das untenstehende Formular aus',
    introduction: 'Wir freuen uns riesig, diesen besonderen Tag mit dir zu feiern! Deine Anwesenheit bedeutet uns die Welt, und wir können es kaum erwarten, diesen wunderschönen Moment mit dir zu teilen. Bitte nimm dir einen Moment Zeit, um das untenstehende Formular auszufüllen, damit wir sicherstellen können, dass alles perfekt für deinen Besuch ist. Wir haben Abschnitte für Ernährungsvorlieben, Musikwünsche und alle besonderen Unterkünfte, die du möglicherweise benötigst, hinzugefügt. Zögere nicht, uns zu kontaktieren, wenn du Fragen hast. Wir freuen uns darauf, dich bald zu sehen!',
    rsvpDetails: 'RSVP Details',
    overnightStay: 'Übernachtung',
    overnightStayQuestion: 'Möchtest du übernachten?',
    overnightStayYes: 'Ja, ich möchte übernachten',
    overnightStayNo: 'Nein, ich möchte nicht übernachten',
    overnightStayNote: 'Die Unterkunft müsst ihr selbst übernehmen.',
    select: 'Auswählen...',
    numberOfGuests: 'Anzahl der Gäste',
    rsvpStatus: 'RSVP Status',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    declined: 'Abgelehnt',
    contactInfo: 'Kontaktinformationen',
    phone: 'Telefon',
    address: 'Adresse',
    musicWish: 'Musikwunsch',
    songRequests: 'Liedwünsche',
    musicPlaceholder: 'Welche Lieder möchtest du auf der Hochzeit hören?',
    dietaryInfo: 'Ernährungsinformationen',
    dietaryRestrictions: 'Ernährungseinschränkungen',
    dietaryPlaceholder: 'z.B. Vegetarisch, Vegan, Glutenfrei',
    allergies: 'Allergien',
    allergiesPlaceholder: 'Bitte liste alle Lebensmittelallergien auf',
    specialRequests: 'Besondere Wünsche',
    specialPlaceholder: 'Besondere Wünsche oder zusätzliche Informationen',
    submitRSVP: 'RSVP absenden',
    saving: 'Wird gespeichert...',
    ourStory: 'Unsere Geschichte',
    invalidLink: 'Ungültiger RSVP-Link',
    invalidLinkMessage: 'Dieser RSVP-Link ist nicht gültig. Bitte überprüfe den Link und versuche es erneut.',
    loadingRSVP: 'Dein RSVP wird geladen...',
    confirmAttendance: 'Bitte bestätige deine Teilnahme',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Dein Wedding Pass',
    yourInvitation: 'Deine Einladung',
    joinOurCelebration: 'Feiere mit uns',
    passIntro: 'Dein kleiner Hochzeitsbegleiter — du kannst jederzeit zurückkommen.',
    loadingWeddingPass: 'Dein Wedding Pass wird geladen...',
    invalidInvitationLinkTitle: 'Ungültiger Einladungslink',
    invalidInvitationLinkMessage: 'Dieser Einladungslink ist nicht gültig. Bitte überprüfe den Link und versuche es erneut.',
    authFailed: 'Authentifizierung fehlgeschlagen',
    authMissing: 'Kein Authentifizierungs-Token verfügbar',
    saveFailed: 'Deine Antwort konnte nicht gespeichert werden. Bitte versuche es erneut.',
    stepLabel: 'Schritt',
    statusPending: 'Noch offen',
    statusYes: 'Dabei',
    statusNo: 'Nicht dabei',
    yes: 'Ja',
    no: 'Nein',
    back: 'Zurück',
    next: 'Weiter',
    continue: 'Weiter',
    skipForNow: 'Später',
    youCanEditAnytime: 'Du kannst deine Antworten später jederzeit ändern.',
    ourBigDay: 'unseren großen Tag',
    qCelebrateOnDate: 'Feierst du unsere Hochzeit mit uns am {{date}}?',
    qCelebrateSub: 'Ein Tap reicht — wir kümmern uns um den Rest.',
    qBothComing: 'Kommt ihr beide?',
    qBothComingSub: 'Damit wir Sitzplätze und Menü planen können.',
    bothOfUs: 'Ja, wir kommen beide',
    justMe: 'Nur ich',
    qGroupHowMany: 'Wie viele von euch kommen?',
    qGroupHowManySub: 'Ihr seid bis zu {{max}} eingeladen — wie viele sollen wir einplanen?',
    groupMaxNote: 'Maximal eingeladen: {{max}}',
    people: 'Personen',
    qOvernight: 'Möchtest du übernachten?',
    qOvernightSub: 'Das hilft uns bei der Planung.',
    overnightNoteSoft: 'Unterkunft organisiert ihr individuell.',
    qDietary: 'Gibt es Ernährungseinschränkungen?',
    qDietarySub: 'Ein kurzer Hinweis reicht.',
    dietaryPlaceholderShort: 'z.B. vegetarisch, glutenfrei, keine Nüsse…',
    qNotes: 'Möchtest du uns noch etwas mitgeben?',
    qNotesSub: 'Optional — was dir wichtig ist.',
    notesPlaceholder: 'Optionaler Hinweis…',
    qAddPhoto: 'Möchtest du ein Foto hinzufügen?',
    qAddPhotoSub: 'Optional — erscheint nach Freigabe in der Galerie.',
    photoOptional: 'Ganz optional. Das geht auch später.',
    photoCaptionPlaceholder: 'Bildunterschrift (optional)',
    uploadAndContinue: 'Hochladen & weiter',
    photoUploaded: 'Foto hochgeladen (wartet auf Freigabe).',
    photoUploadFailed: 'Foto-Upload fehlgeschlagen. Bitte versuche es erneut.',
    doneTitle: 'Alles erledigt',
    doneSub: 'Danke — dein Wedding Pass ist gespeichert.',
    doneYesTitle: 'Wir freuen uns so, dass du dabei bist',
    doneYesSub: 'Dein Wedding Pass ist gespeichert — bis bald.',
    doneNoTitle: 'Danke fürs Bescheid geben',
    doneNoSub: 'Dein Wedding Pass ist gespeichert. Details findest du unten.',
    addToCalendar: 'In den Kalender',
    calendarNotConfigured: 'Kalenderexport ist noch nicht konfiguriert (wedding_date_iso fehlt).',
    calendarEventTitle: 'Hochzeitsfeier',
    calendarEventDescription: 'Unser großer Tag — Details in deinem Wedding Pass.',
    saveThisPageTitle: 'Tipp:',
    saveThisPageBody: 'Setze ein Lesezeichen, damit du jederzeit zurückkommst.',
    whyReturnTitle: 'Warum zurückkommen?',
    whyReturnBody: 'Wir aktualisieren diese Seite laufend mit allen Infos.',
    openFullInfo: 'Zur Infoseite',
    editAnswers: 'Antworten ändern',
    tabNeedToKnow: 'Alles Wichtige',
    tabVenue: 'Hochzeitslocation',
    tabDayItself: 'Der Tag',
    tabYourEvening: 'Dein Abend',
    comingSoon: 'Kommt bald',
    needToKnowTitle: 'Alles Wichtige',
    needToKnowBody: 'Ort, Anreise, Geschenke und Dresscode findest du hier.',
    giftDressCodeTitle: 'Geschenke & Dresscode',
    giftDressCodeBody: 'Die Details teilen wir hier näher am Datum.',
    dayItselfTitle: 'Ablauf',
  },
  fr: {
    welcome: 'Bienvenue',
    rsvp: 'RSVP',
    hi: 'Salut',
    fillForm: 'Veuillez remplir le formulaire ci-dessous',
    introduction: "Nous sommes absolument ravis de célébrer ce jour spécial avec vous! Votre présence signifie tout pour nous, et nous avons hâte de partager ce beau moment ensemble. Veuillez prendre un moment pour remplir le formulaire ci-dessous afin que nous puissions nous assurer que tout est parfait pour votre visite. Nous avons inclus des sections pour les préférences alimentaires, les demandes musicales et tout hébergement spécial dont vous pourriez avoir besoin. N'hésitez pas à nous contacter si vous avez des questions. Nous avons hâte de vous voir bientôt!",
    rsvpDetails: 'Détails RSVP',
    overnightStay: 'Hébergement',
    overnightStayQuestion: 'Souhaitez-vous rester pour la nuit?',
    overnightStayYes: 'Oui, je souhaite rester pour la nuit',
    overnightStayNo: 'Non, je ne souhaite pas rester pour la nuit',
    overnightStayNote: 'Vous devez organiser l\'hébergement vous-mêmes.',
    select: 'Sélectionner...',
    numberOfGuests: 'Nombre d\'invités',
    rsvpStatus: 'Statut RSVP',
    pending: 'En attente',
    confirmed: 'Confirmé',
    declined: 'Refusé',
    contactInfo: 'Informations de contact',
    phone: 'Téléphone',
    address: 'Adresse',
    musicWish: 'Souhait musical',
    songRequests: 'Demandes de chansons',
    musicPlaceholder: 'Quelles chansons aimeriez-vous entendre au mariage?',
    dietaryInfo: 'Informations diététiques',
    dietaryRestrictions: 'Restrictions alimentaires',
    dietaryPlaceholder: 'par ex. Végétarien, Végétalien, Sans gluten',
    allergies: 'Allergies',
    allergiesPlaceholder: 'Veuillez lister toutes les allergies alimentaires',
    specialRequests: 'Demandes spéciales',
    specialPlaceholder: 'Toute demande spéciale ou information supplémentaire',
    submitRSVP: 'Soumettre RSVP',
    saving: 'Enregistrement...',
    ourStory: 'Notre histoire',
    invalidLink: 'Lien RSVP invalide',
    invalidLinkMessage: 'Ce lien RSVP n\'est pas valide. Veuillez vérifier le lien et réessayer.',
    loadingRSVP: 'Chargement de votre RSVP...',
    confirmAttendance: 'Veuillez confirmer votre présence',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Votre Pass Mariage',
    yourInvitation: 'Votre invitation',
    joinOurCelebration: 'Célébrez avec nous',
    passIntro: 'Un compagnon de mariage auquel vous pouvez revenir à tout moment.',
    loadingWeddingPass: 'Chargement de votre Pass Mariage...',
    invalidInvitationLinkTitle: 'Lien d’invitation invalide',
    invalidInvitationLinkMessage: 'Ce lien d’invitation n’est pas valide. Veuillez vérifier le lien et réessayer.',
    authFailed: 'Échec de l’authentification',
    authMissing: 'Aucun jeton d’authentification disponible',
    saveFailed: 'Impossible d’enregistrer votre réponse. Veuillez réessayer.',
    stepLabel: 'Étape',
    statusPending: 'Pas encore décidé',
    statusYes: 'Présent',
    statusNo: 'Absent',
    yes: 'Oui',
    no: 'Non',
    back: 'Retour',
    next: 'Suivant',
    continue: 'Continuer',
    skipForNow: 'Plus tard',
    youCanEditAnytime: 'Vous pourrez modifier vos réponses plus tard.',
    ourBigDay: 'notre grand jour',
    qCelebrateOnDate: 'Célébrerez-vous notre mariage avec nous le {{date}} ?',
    qCelebrateSub: 'Un simple clic — on s’occupe du reste.',
    qBothComing: 'Venez-vous tous les deux ?',
    qBothComingSub: 'Pour nous aider à organiser les places et le menu.',
    bothOfUs: 'Oui, tous les deux',
    justMe: 'Seulement moi',
    qGroupHowMany: 'Combien serez-vous à venir ?',
    qGroupHowManySub: 'Jusqu’à {{max}} invités — combien devons-nous prévoir ?',
    groupMaxNote: 'Invités max : {{max}}',
    people: 'personnes',
    qOvernight: 'Resterez-vous pour la nuit ?',
    qOvernightSub: 'Cela nous aide pour l’organisation.',
    overnightNoteSoft: 'L’hébergement est organisé individuellement.',
    qDietary: 'Des restrictions alimentaires ?',
    qDietarySub: 'Une petite note suffit.',
    dietaryPlaceholderShort: 'ex. végétarien, sans gluten, pas de noix…',
    qNotes: 'Autre chose à nous dire ?',
    qNotesSub: 'Optionnel — partagez ce qui compte.',
    notesPlaceholder: 'Note optionnelle…',
    qAddPhoto: 'Envie d’ajouter une photo ?',
    qAddPhotoSub: 'Optionnel — elle apparaîtra dans la galerie après validation.',
    photoOptional: 'Totalement optionnel. Vous pourrez le faire plus tard.',
    photoCaptionPlaceholder: 'Légende (optionnel)',
    uploadAndContinue: 'Téléverser & continuer',
    photoUploaded: 'Photo téléversée (en attente de validation).',
    photoUploadFailed: 'Échec du téléversement. Veuillez réessayer.',
    doneTitle: 'Tout est prêt',
    doneSub: 'Merci — votre Pass Mariage est enregistré.',
    doneYesTitle: 'Nous sommes si heureux de vous compter parmi nous',
    doneYesSub: 'Votre Pass Mariage est enregistré — à très vite.',
    doneNoTitle: 'Merci de nous avoir prévenus',
    doneNoSub: 'Votre Pass Mariage est enregistré. Vous pouvez consulter les détails ci-dessous.',
    addToCalendar: 'Ajouter au calendrier',
    calendarNotConfigured: 'Export calendrier non configuré (wedding_date_iso manquant).',
    calendarEventTitle: 'Célébration de mariage',
    calendarEventDescription: 'Notre grand jour — détails dans votre Pass Mariage.',
    saveThisPageTitle: 'Astuce :',
    saveThisPageBody: 'Ajoutez cette page en favori pour y revenir facilement.',
    whyReturnTitle: 'Pourquoi revenir ?',
    whyReturnBody: 'Nous mettrons cette page à jour avec toutes les infos utiles.',
    openFullInfo: 'Ouvrir la page d’infos',
    editAnswers: 'Modifier mes réponses',
    tabNeedToKnow: 'À savoir',
    tabVenue: 'Lieu',
    tabDayItself: 'Le jour J',
    tabYourEvening: 'Votre soirée',
    comingSoon: 'Bientôt disponible',
    needToKnowTitle: 'À savoir',
    needToKnowBody: 'Lieu, voyage, cadeaux et tenue seront ici.',
    giftDressCodeTitle: 'Cadeaux & tenue',
    giftDressCodeBody: 'Nous partagerons les détails à l’approche du jour J.',
    dayItselfTitle: 'Planning',
  },
}

export function LanguageProvider({ children, initialLanguage = 'en' }) {
  const [language, setLanguage] = useState(() => {
    // Try to get from localStorage or use initial language
    const saved = localStorage.getItem('guest_language')
    return saved || initialLanguage
  })

  // Fetch content from database
  const { data: contentItems } = useQuery({
    queryKey: ['content', 'public', language],
    queryFn: () => api.get(`/content?lang=${language}`).then((res) => res.data),
    enabled: true, // Always fetch
  })

  useEffect(() => {
    localStorage.setItem('guest_language', language)
  }, [language])

  const t = (key) => {
    // First try to get from database content
    if (contentItems) {
      const contentItem = contentItems.find(item => item.key === key)
      if (contentItem && contentItem.content) {
        return contentItem.content
      }
    }
    
    // Fallback to hardcoded translations
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

