import { createContext, useContext, useState, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import api from '../lib/api'

const LanguageContext = createContext()

const translations = {
  en: {
    welcome: 'Welcome',
    rsvp: 'RSVP',
    hi: 'Hi',
    fillForm: 'Please fill out the form below',
    introduction: "We are absolutely thrilled to celebrate this special day with you! Your presence means the world to us, and we can't wait to share this beautiful moment together. Please take a moment to fill out the form below so we can make sure everything is perfect for your visit. We've included sections for dietary preferences, music requests, and any special accommodations you might need. Don't hesitate to reach out if you have any questions. We're looking forward to seeing you soon!",
    rsvpDetails: 'RSVP Details',
    overnightStay: 'Overnight Stay',
    overnightStayQuestion: 'Would you like to stay overnight?',
    overnightStayYes: 'Yes, I would like to stay overnight',
    overnightStayNo: 'No, I would not like to stay overnight',
    overnightStayNote: 'You need to arrange accommodation yourselves.',
    select: 'Select...',
    numberOfGuests: 'Number of Guests',
    rsvpStatus: 'RSVP Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    declined: 'Declined',
    contactInfo: 'Contact Information',
    phone: 'Phone',
    address: 'Address',
    musicWish: 'Music Wish',
    songRequests: 'Song Requests',
    musicPlaceholder: 'What songs would you like to hear at the wedding?',
    dietaryInfo: 'Dietary Information',
    dietaryRestrictions: 'Dietary Restrictions',
    dietaryPlaceholder: 'e.g., Vegetarian, Vegan, Gluten-free',
    allergies: 'Allergies',
    allergiesPlaceholder: 'Please list any food allergies',
    specialRequests: 'Special Requests',
    specialPlaceholder: 'Any special requests or additional information',
    submitRSVP: 'Submit RSVP',
    saving: 'Saving...',
    ourStory: 'Our Story',
    invalidLink: 'Invalid RSVP Link',
    invalidLinkMessage: 'This RSVP link is not valid. Please check the link and try again.',
    loadingRSVP: 'Loading your RSVP...',
    confirmAttendance: 'Please confirm your attendance',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Your Wedding Pass',
    yourInvitation: 'Your Invitation',
    joinOurCelebration: 'Join Our Celebration',
    passIntro: 'A little wedding companion you can return to anytime.',
    loadingWeddingPass: 'Loading your Wedding Pass...',
    invalidInvitationLinkTitle: 'Invalid Invitation Link',
    invalidInvitationLinkMessage: 'This invitation link is not valid. Please check the link and try again.',
    invalidInvitationContactHint: 'If you believe this is an error, please contact the bride and groom for a new invitation link.',
    authFailed: 'Failed to authenticate',
    authMissing: 'No authentication token available',
    saveFailed: 'Could not save your answer. Please try again.',
    stepLabel: 'Step',
    statusPending: 'Not decided yet',
    statusYes: 'Coming',
    statusNo: 'Not coming',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    next: 'Next',
    continue: 'Continue',
    changeToNo: 'Change to No',
    skipForNow: 'Skip for now',
    youCanEditAnytime: 'You can change your answers until 30 April 2026.',
    rsvpDeadlinePassed: 'The RSVP deadline (30 April 2026) has passed. Changes are no longer possible.',
    rsvpDeadlinePassedSub: 'If you need to make changes, please contact the bride and groom directly.',
    rsvpCurrentStatus: 'Your current RSVP status:',
    contactCoupleFlipHint: 'Tap to see contact details',
    contactCoupleDescription: 'Your well-being is very close to our hearts. If there is anything you would like to clarify in connection with our wedding \u2014 from organisational details to personal matters \u2014 please do not hesitate to contact us at any time. We are happy to be there for you.',
    contactWitnessesDescription: 'For ideas about the wedding program, surprises, speeches, games, or special contributions, please reach out to our wonderful witnesses. They look forward to your creative thoughts and are happy to help coordinate with lots of heart.',
    ourBigDay: 'our big day',
    attendanceVenueHint: 'Seerose Resort & Spa, Hallwilersee',
    doneOvernightHint: 'If you would like to stay overnight, use the booking code for the Seerose Resort & Spa. You will find all details in the Accommodation & Travel section.',
    qCelebrateOnDate: 'Will you celebrate our wedding with us on {{date}}?',
    qCelebrateSub: 'Just one tap — we’ll take care of the rest.',
    qBothComing: 'Will both of you be joining?',
    qBothComingSub: 'So we can plan the seats and the menu.',
    bothOfUs: 'Yes, both of us',
    justMe: 'Just me',
    onlyName: 'Only {{name}}',
    name1: 'Name 1',
    name2: 'Name 2',
    qGroupHowMany: 'How many of you will be coming?',
    qGroupHowManySub: 'Up to {{max}} invited — what should we plan for?',
    groupMaxNote: 'Max invited: {{max}}',
    people: 'people',
    qGroupWhoComing: 'Who will be coming?',
    qGroupWhoComingSub: 'Select everyone who’s joining us.',
    selectedCount: '{{count}} of {{max}} selected',
    qOvernight: 'Will you stay overnight?',
    qOvernightSub: 'This helps us plan the sleeping arrangements.',
    overnightNoteSoft: 'Accommodation is organized individually.',
    overnightAccommodationHint: 'You can find more details in the Accommodation & Travel section on the wedding page.',
    qDietary: 'Any dietary restrictions?',
    qDietarySub: 'One short note is perfect.',
    dietaryPlaceholderShort: 'e.g. vegetarian, gluten-free, no nuts…',
    qNotes: 'Anything else you’d like us to know?',
    qNotesSub: 'Optional — let us know what would make your experience special.',
    notesPlaceholder: 'e.g. favorite song, seating preferences…',
    finish: 'Finish',
    qAddPhoto: 'Want to add a photo?',
    qAddPhotoSub: 'Optional — it’ll appear in the guest gallery after approval.',
    photoOptional: 'Totally optional. You can also do this later.',
    photoCaptionPlaceholder: 'Caption (optional)',
    uploadAndContinue: 'Upload & continue',
    photoUploaded: 'Photo uploaded (awaiting approval).',
    photoUploadFailed: 'Photo upload failed. Please try again.',
    doneTitle: 'You’re all set',
    doneSub: 'Thanks — your Wedding Pass is saved.',
    doneYesTitle: 'We’re so happy you’re joining us',
    doneYesSub: 'Your Wedding Pass is saved — see you soon.',
    doneNoTitle: 'Thank you for letting us know',
    doneNoSub: 'Your Wedding Pass is saved. You can still check details below.',
    addToCalendar: 'Add to calendar',
    saveThisPageButton: 'Save this page',
    savePageTitle: 'Save this page',
    savePageInstall: 'Install / Add to Home Screen',
    savePageInstructions: 'Bookmark this page (Ctrl/Cmd + D) or use the star in your browser.',
    savePageInstructions_ios: 'Tap Share, then "Add to Home Screen" or bookmark.',
    savePageInstructions_android: 'Tap Menu (⋮), then "Add to Home screen" or "Install app".',
    savePageInstructions_desktop: 'Press Ctrl/Cmd + D to bookmark, or use the star in your address bar.',
    savePageCopyLink: 'Copy link',
    savePageCopied: 'Copied!',
    savePageHint: 'Please bookmark this page (Ctrl/Cmd + D).',
    calendarNotConfigured: 'Calendar export is not configured yet (missing wedding_date_iso).',
    declineConfirmTitle: 'Are you sure you won’t attend?',
    declineConfirmBody: 'We just want to double-check — you can always change this later.',
    declineConfirmYes: "Yes, I'm sure",
    declineConfirmBack: 'Go back',
    declinedSadTitle: "It's sad to see you leave 😢",
    declinedSadSub: 'Your Wedding Pass is saved. If anything changes, you can always come back.',
    calendarEventTitle: 'Wedding Celebration',
    calendarEventDescription: 'Our big day — details in your Wedding Pass.',
    saveThisPageTitle: 'Tip:',
    saveThisPageBody: 'Bookmark this page so you can come back anytime.',
    whyReturnTitle: 'Why return?',
    whyReturnBody: 'We’ll keep updating this page with everything you need for the day.',
    openFullInfo: 'Open full info page',
    editAnswers: 'Update my answers',
    tabNeedToKnow: 'All you need to know',
    tabVenue: 'Wedding venue',
    tabDayItself: 'The day itself',
    tabYourEvening: 'Your evening',
    comingSoon: 'Coming soon',
    needToKnowTitle: 'All you need to know',
    needToKnowBody: 'Location, travel tips, gifts and dress code will live here.',
    giftDressCodeTitle: 'Gifts & dress code',
    giftDressCodeBody: 'We’ll share the details here as we get closer to the date.',
    dayItselfTitle: 'Timeline',

    // Guest portal - timeline component
    timelineTitle: 'Wedding Program',
    timelineLoading: 'Loading timeline...',
    timelineEmpty: 'No events scheduled yet.',
    dressCodeLabel: 'Dress code:',
    
    // Guest portal - section labels
    venueLabel: 'Venue',
    dresscodeLabel: 'Dresscode',
    agendaLabel: 'Agenda',

    // Guest portal - Gift Registry
    giftRegistryTitle: 'Gift Registry',
    giftRegistryLoading: 'Loading registry...',
    giftRegistryIntro:
      'Your presence at our wedding is the greatest gift of all. However, if you wish to honor us with a gift, we have registered at the following places:',
    giftRegistryVisit: 'Visit registry',
    giftRegistryProgress: 'Progress',
    giftRegistryCashHint: 'Contributions can be made through the link provided by the couple.',
    giftRegistryExperienceHint: 'Help us create unforgettable memories!',
    giftRegistryEmpty: 'No registry items available yet.',
    giftRegistryTypeExternal: 'Registry link',
    giftRegistryTypeCash: 'Cash fund',
    giftRegistryTypeExperience: 'Experience fund',
    giftRegistryTypeDefault: 'Gift',

    // Guest portal - Info page labels
    inviteTypeIndividual: 'Individual',
    inviteTypeCouple: 'Couple',
    inviteTypeGroup: 'Group',
    guestInfoTitle: 'Wedding Information',
    guestInfoSubtitle: 'Everything you need to know',
    guestInfoChangeTitle: 'Change your information',
    guestInfoChangeBody: 'You can review and update your Wedding Pass at any time.',
    guestInfoChangeCardSubtitle: 'Review and update your Wedding Pass',
    guestInfoCurrentAnswers: 'Your current answers',
    guestInfoComing: 'Coming',
    guestInfoAttending: 'Are you attending the wedding?',
    guestInfoInviteType: 'Invite type',
    guestInfoGuests: 'Guests',
    guestInfoOvernight: 'Overnight stay',
    bookingLinkHint: 'Book with our special rate for reduced cost.',
    bookingLinkClick: 'Click here to book.',
    bookingLinkComingSoon: 'Booking information coming soon.',
    guestInfoDietary: 'Dietary',
    guestInfoProvided: 'Provided',
    guestInfoDietaryDetails: 'Dietary details',
    guestInfoNotes: 'Notes',
    guestInfoCancelEditing: 'Cancel editing',
    guestInfoEditHere: 'Edit here',
    guestInfoOpenPass: 'Open your Wedding Pass',
    guestInfoBackToInfo: 'Back to information',
    guestInfoEditAnswers: 'Edit your answers',
    guestInfoWhoIsComing: 'Who is coming?',
    guestInfoWhoIsComingHint: 'Leave at least one selected if you are coming.',
    guestInfoDietaryRestrictions: 'Dietary restrictions',
    guestInfoSaveChanges: 'Save changes',

    // Guest portal - Travel & Accommodation
    guestTravelTitle: 'Travel & Accommodation',
    guestTravelCardSubtitle: 'Hotel and directions',
    travelSectionTitle: 'Getting There',
    travelByCar: 'By Car',
    travelByPublicTransport: 'By Public Transport',
    travelCarDirections: 'Motorway exit A1 Lenzburg, direction Wohlen, Villmergen, Sarmenstorf, Meisterschwanden. The hotel is located outside Meisterschwanden, direction Aesch/Lucerne.',
    travelCarTimes: 'From Zurich 45 minutes\nFrom Bern 1 hour 20 minutes\nFrom Basel 1 hour\nFrom Lucerne 40 minutes',
    travelCarParking: '500 outdoor parking spaces\n20 paid underground parking spaces including 4 charging stations 22 kW Type 2 socket (charging costs as per tariff)',
    travelCarParkingTitle: 'Parking & EV Charging',
    travelPublicTransportDirections: 'From the train stations Wohlen and Lenzburg there is a PostBus connection to the Meisterschwanden Oberdorf stop. From there, overnight guests will be picked up free of charge by a shuttle service. Please let us know your exact arrival time in advance.',
    travelNoteTitle: 'Important travel note',
    travelNoteBody: 'On 10 October 2026, the Hallwilerseelauf takes place around Lake Hallwil. Access roads and parking at the Seerose remain fully available. However, the race route passes through the hotel. Please allow extra travel time.',
    travelNoteLink: 'More info',
    guestAccommodationVenueTitle: 'Accommodation',
    guestAccommodationDetailsFallback: 'Accommodation details will be shared here.',
    guestAccommodationOpenWebsite: 'Open website',
    guestAccommodationBookingTitle: 'Room Booking',
    guestAccommodationBookNow: 'Book your room',
    guestAccommodationBookingStayTuned: 'Stay tuned for booking information',

    // Guest portal - Event & Gifts
    guestGiftsTitle: 'Event & Gifts',
    guestGiftsCardSubtitle: 'Schedule and registry',
    guestGiftsScheduleTitle: 'Event schedule',
    guestGiftsFeaturedEvent: 'Selected timeline',
    guestGiftsDetailsTitle: 'Details',

    // Guest portal - Gallery
    guestGalleryTitle: 'Photo Gallery',
    guestGalleryCardSubtitle: 'Share your photos',

    // Guest portal - Contact
    guestContactTitle: 'Contact us',
    guestContactCardSubtitle: 'Send us a message',

    // Guest website top navigation
    guestNavHello: 'Hello',
    guestNavWeddingPass: 'Wedding Pass',
    guestNavTravelAccommodation: 'Accommodation & Travel',
    guestNavWeddingProgram: 'Wedding Program',
    guestNavGifts: 'Gifts',
    guestNavPhotos: 'Photos',
    guestNavContact: 'Contact',
    guestGiftsInfoTitle: 'Gifts',
    guestGiftsInfoBody:
      'Your presence means the world to us. If you’d like to give something, you’ll find the details here.',
    giftWishlistTitle: "Things we'd like to do",
    activitySkydiving: 'Skydiving',
    activityGolf: 'Golf',
    activityTheater: 'Theater',
    activityTennis: 'Tennis',
    activityDining: 'Fine Dining',
    giftIbanLabel: 'Bank Transfer',
    copied: 'Copied!',
    copyToClipboard: 'Copy to clipboard',

    // Photo gallery
    photoGalleryTitle: 'Photo Gallery',
    photoGalleryLoading: 'Loading gallery...',
    photoGallerySharedFolderTitle: 'Shared photo folder',
    photoGalleryRedirecting: 'Redirecting you to the shared folder…',
    photoGalleryOpenFolder: 'Open folder',
    photoGalleryUploadToFolder: 'Upload to folder',
    photoGalleryRedirectHint: 'Share your pictures with us!',
    photoGalleryUploadTitle: 'Upload a photo',
    photoGalleryCaptionPlaceholder: 'Add a caption (optional)',
    photoGalleryUploading: 'Uploading...',
    photoGalleryUploadButton: 'Upload photo',
    photoGalleryDropHint: 'Drag and drop a photo here, or click to browse',
    photoGallerySelectPhoto: 'Select photo',
    photoGalleryUploadSuccess: 'Photo uploaded! It will be visible after admin approval.',
    photoGalleryUploadFailed: 'Failed to upload photo',
    photoGalleryInvalidFile: 'Please select an image file',
    photoGalleryTooLarge: 'Image size must be less than 10MB',

    // Contact form
    contactTitle: 'Contact us',
    contactIntro: "Have a question? Send us a message and we'll get back to you as soon as possible.",
    contactSentTitle: "Message sent successfully! We'll get back to you soon.",
    contactSendFailed: 'Failed to send message',
    contactSubjectLabel: 'Subject *',
    contactMessageLabel: 'Message *',
    contactSubjectPlaceholder: 'e.g., Question about accommodations',
    contactMessagePlaceholder: 'Write your message here...',
    contactSending: 'Sending...',
    contactSendButton: 'Send message',
    contactRetry: 'Retry',

    // Contact toggle & witness cards
    contactBrideGroom: 'Contact the bride and groom',
    contactWitnesses: 'Contact the Maid of Honor & Best Man',
    witnessCardFlipHint: 'Tap to see contact info',
    witnessPhoneLabel: 'Phone',

    // Guest login
    guestLoginTitle: 'Welcome back',
    guestLoginSubtitle: 'Please sign in to access your RSVP',
    guestLoginUsername: 'Username',
    guestLoginPassword: 'Password',
    guestLoginUsernamePlaceholder: 'Enter your username',
    guestLoginPasswordPlaceholder: 'Enter your password',
    guestLoginSigningIn: 'Signing in...',
    guestLoginSignIn: 'Sign in',
    guestLoginFailed: 'Login failed. Please check your credentials.',

    // Guest registration
    guestRegisterInvalidInvitationTitle: 'Invalid invitation',
    guestRegisterInvalidInvitationBody: 'No invitation token found. Please use the link from your invitation email.',
    guestRegisterGoToLogin: 'Go to login',
    guestRegisterValidating: 'Validating invitation...',
    guestRegisterYoureInvited: "You're invited!",
    guestRegisterDearName: 'Dear {{name}},',
    guestRegisterDearGuest: 'Dear Guest,',
    guestRegisterHeroBody: "We're thrilled to invite you to celebrate our special day with us!",
    guestRegisterCompleteTitle: 'Complete your registration',
    guestRegisterCompleteSubtitle: 'Please fill out the form below to create your account and RSVP',
    guestRegisterPlusOneLabel: 'Plus one:',
    guestRegisterPlusOneBody: 'You can bring {{count}} guest{{plural}}',
    guestRegisterFirstName: 'First name *',
    guestRegisterLastName: 'Last name *',
    guestRegisterPhone: 'Phone number',
    guestRegisterPasswordHint: 'Must be at least 6 characters',
    guestRegisterConfirmPassword: 'Confirm password *',
    guestRegisterCreatingAccount: 'Creating account...',
    guestRegisterCreateContinue: 'Create account & continue',
    guestRegisterPasswordsNoMatch: 'Passwords do not match',
    guestRegisterPasswordTooShort: 'Password must be at least 6 characters',
  },
  de: {
    welcome: 'Willkommen',
    rsvp: 'RSVP',
    hi: 'Hallo',
    fillForm: 'Bitte fülle das untenstehende Formular aus',
    introduction: 'Wir freuen uns riesig, diesen besonderen Tag mit dir zu feiern! Deine Anwesenheit bedeutet uns die Welt, und wir können es kaum erwarten, diesen wunderschönen Moment mit dir zu teilen. Bitte nimm dir einen Moment Zeit, um das untenstehende Formular auszufüllen, damit wir sicherstellen können, dass alles perfekt für deinen Besuch ist. Wir haben Abschnitte für Ernährungsvorlieben, Musikwünsche und alle besonderen Unterkünfte, die du möglicherweise benötigst, hinzugefügt. Zögere nicht, uns zu kontaktieren, wenn du Fragen hast. Wir freuen uns darauf, dich bald zu sehen!',
    rsvpDetails: 'RSVP Details',
    overnightStay: 'Übernachtung',
    overnightStayQuestion: 'Möchtest du übernachten?',
    overnightStayYes: 'Ja, ich möchte übernachten',
    overnightStayNo: 'Nein, ich möchte nicht übernachten',
    overnightStayNote: 'Die Unterkunft müsst ihr selbst übernehmen.',
    select: 'Auswählen...',
    numberOfGuests: 'Anzahl der Gäste',
    rsvpStatus: 'RSVP Status',
    pending: 'Ausstehend',
    confirmed: 'Bestätigt',
    declined: 'Abgelehnt',
    contactInfo: 'Kontaktinformationen',
    phone: 'Telefon',
    address: 'Adresse',
    musicWish: 'Musikwunsch',
    songRequests: 'Liedwünsche',
    musicPlaceholder: 'Welche Lieder möchtest du auf der Hochzeit hören?',
    dietaryInfo: 'Ernährungsinformationen',
    dietaryRestrictions: 'Ernährungseinschränkungen',
    dietaryPlaceholder: 'z.B. Vegetarisch, Vegan, Glutenfrei',
    allergies: 'Allergien',
    allergiesPlaceholder: 'Bitte liste alle Lebensmittelallergien auf',
    specialRequests: 'Besondere Wünsche',
    specialPlaceholder: 'Besondere Wünsche oder zusätzliche Informationen',
    submitRSVP: 'RSVP absenden',
    saving: 'Wird gespeichert...',
    ourStory: 'Unsere Geschichte',
    invalidLink: 'Ungültiger RSVP-Link',
    invalidLinkMessage: 'Dieser RSVP-Link ist nicht gültig. Bitte überprüfe den Link und versuche es erneut.',
    loadingRSVP: 'Dein RSVP wird geladen...',
    confirmAttendance: 'Bitte bestätige deine Teilnahme',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Dein Wedding Pass',
    yourInvitation: 'Deine Einladung',
    joinOurCelebration: 'Feiere mit uns',
    passIntro: 'Dein kleiner Hochzeitsbegleiter — du kannst jederzeit zurückkommen.',
    loadingWeddingPass: 'Dein Wedding Pass wird geladen...',
    invalidInvitationLinkTitle: 'Ungültiger Einladungslink',
    invalidInvitationLinkMessage: 'Dieser Einladungslink ist nicht gültig. Bitte überprüfe den Link und versuche es erneut.',
    invalidInvitationContactHint: 'Falls du glaubst, dass es sich um einen Fehler handelt, kontaktiere bitte das Brautpaar für einen neuen Einladungslink.',
    authFailed: 'Authentifizierung fehlgeschlagen',
    authMissing: 'Kein Authentifizierungs-Token verfügbar',
    saveFailed: 'Deine Antwort konnte nicht gespeichert werden. Bitte versuche es erneut.',
    stepLabel: 'Schritt',
    statusPending: 'Noch offen',
    statusYes: 'Dabei',
    statusNo: 'Nicht dabei',
    yes: 'Ja',
    no: 'Nein',
    back: 'Zurück',
    next: 'Weiter',
    continue: 'Weiter',
    changeToNo: 'Nein, doch nicht',
    skipForNow: 'Später',
    // Singular (du) forms
    youCanEditAnytime: 'Du kannst deine Antworten bis zum 30. April 2026 \u00e4ndern.',
    rsvpDeadlinePassed: 'Die Anmeldefrist (30. April 2026) ist abgelaufen. \u00c4nderungen sind nicht mehr m\u00f6glich.',
    rsvpDeadlinePassedSub: 'Falls du \u00c4nderungen ben\u00f6tigst, wende dich bitte direkt an das Brautpaar.',
    rsvpCurrentStatus: 'Dein aktueller RSVP-Status:',
    contactCoupleFlipHint: 'Antippen, um Kontaktdaten zu sehen',
    contactCoupleDescription: 'Euer Wohlbefinden liegt uns sehr am Herzen. Wenn es also irgendetwas gibt, das ihr im Zusammenhang mit unserer Hochzeit kl\u00e4ren m\u00f6chtet \u2013 von organisatorischen Details bis hin zu pers\u00f6nlichen Anliegen \u2013 meldet euch jederzeit gerne bei uns. Wir sind mit Freude f\u00fcr euch da.',
    contactWitnessesDescription: 'F\u00fcr Ideen rund um das Hochzeitsprogramm, \u00dcberraschungen, Reden, Spiele oder besondere Beitr\u00e4ge wendet euch gerne an unsere wunderbaren Trauzeugen. Sie freuen sich \u00fcber eure kreativen Gedanken und helfen mit viel Herz bei der Koordination.',
    ourBigDay: 'unseren grossen Tag',
    attendanceVenueHint: 'Seerose Resort & Spa, Hallwilersee',
    doneOvernightHint: 'Falls ihr \u00fcbernachten m\u00f6chtet, nutzt den Buchungscode f\u00fcr das Seerose Resort & Spa. Alle Details findet ihr im Bereich Unterkunft & Anreise.',
    qCelebrateOnDate: 'Feierst du unsere Hochzeit mit uns am {{date}}?',
    qCelebrateSub: 'Ein Tap reicht — wir kümmern uns um den Rest.',
    // Plural (ihr/euch) forms for couples/groups
    youCanEditAnytime_plural: 'Ihr k\u00f6nnt eure Antworten bis zum 30. April 2026 \u00e4ndern.',
    qCelebrateOnDate_plural: 'Feiert ihr unsere Hochzeit mit uns am {{date}}?',
    qCelebrateSub_plural: 'Ein Tap reicht — wir kümmern uns um den Rest.',
    qBothComing: 'Kommt ihr beide?',
    qBothComingSub: 'Damit wir Sitzplätze und Menü planen können.',
    bothOfUs: 'Ja, wir kommen beide',
    justMe: 'Nur ich',
    onlyName: 'Nur {{name}}',
    name1: 'Name 1',
    name2: 'Name 2',
    qGroupHowMany: 'Wie viele von euch kommen?',
    qGroupHowManySub: 'Ihr seid bis zu {{max}} eingeladen — wie viele sollen wir einplanen?',
    groupMaxNote: 'Maximal eingeladen: {{max}}',
    people: 'Personen',
    qGroupWhoComing: 'Wer kommt mit?',
    qGroupWhoComingSub: 'Wählt alle aus, die dabei sind.',
    selectedCount: '{{count}} von {{max}} ausgewählt',
    // Singular (du) forms
    qOvernight: 'Möchtest du übernachten?',
    qOvernightSub: 'Das hilft uns bei der Planung.',
    qDietary: 'Gibt es etwas, dass wir zu deiner Ernährung beachten sollen?',
    qDietarySub: 'Ein kurzer Hinweis reicht.',
    qNotes: 'Hast du einen Musikwunsch oder andere Anliegen?',
    qNotesSub: 'Optional — sag uns, was dir wichtig ist.',
    // Plural (ihr/euch) forms for couples/groups
    qOvernight_plural: 'Möchtet ihr übernachten?',
    qOvernightSub_plural: 'Das hilft uns bei der Planung.',
    qDietary_plural: 'Gibt es etwas, dass wir zu eurer Ernährung beachten sollen?',
    qDietarySub_plural: 'Ein kurzer Hinweis reicht.',
    qNotes_plural: 'Habt ihr einen Musikwunsch oder andere Anliegen?',
    qNotesSub_plural: 'Optional — sagt uns, was euch wichtig ist.',
    overnightNoteSoft: 'Unterkunft organisiert ihr individuell.',
    overnightAccommodationHint: 'Weitere Informationen findest du im Bereich Unterkunft & Anreise auf der Hochzeitsseite.',
    dietaryPlaceholderShort: 'z.B. vegetarisch, glutenfrei, keine Nüsse…',
    notesPlaceholder: 'z.B. Lieblingslied, Sitzplatzwunsch…',
    finish: 'Fertig',
    qAddPhoto: 'Möchtest du ein Foto hinzufügen?',
    qAddPhotoSub: 'Optional — erscheint nach Freigabe in der Galerie.',
    photoOptional: 'Ganz optional. Das geht auch später.',
    photoCaptionPlaceholder: 'Bildunterschrift (optional)',
    uploadAndContinue: 'Hochladen & weiter',
    photoUploaded: 'Foto hochgeladen (wartet auf Freigabe).',
    photoUploadFailed: 'Foto-Upload fehlgeschlagen. Bitte versuche es erneut.',
    doneTitle: 'Alles erledigt',
    doneSub: 'Danke — dein Wedding Pass ist gespeichert.',
    doneYesTitle: 'Wir freuen uns so, dass du dabei bist',
    doneYesSub: 'Dein Wedding Pass ist gespeichert — bis bald.',
    doneNoTitle: 'Danke fürs Bescheid geben',
    doneNoSub: 'Dein Wedding Pass ist gespeichert. Details findest du unten.',
    addToCalendar: 'In den Kalender',
    saveThisPageButton: 'Diese Seite speichern',
    savePageTitle: 'Diese Seite speichern',
    savePageInstall: 'Installieren / Zur Startseite hinzufügen',
    savePageInstructions: 'Lesezeichen setzen (Strg/Cmd + D) oder Stern im Browser nutzen.',
    savePageInstructions_ios: 'Teilen antippen, dann "Zum Home-Bildschirm" oder Lesezeichen.',
    savePageInstructions_android: 'Menü (⋮) antippen, dann "Zum Startbildschirm" oder "App installieren".',
    savePageInstructions_desktop: 'Strg/Cmd + D zum Lesezeichen setzen oder Stern in der Adressleiste.',
    savePageCopyLink: 'Link kopieren',
    savePageCopied: 'Kopiert!',
    savePageHint: 'Bitte speichere diese Seite als Lesezeichen (Strg/Cmd + D).',
    calendarNotConfigured: 'Kalenderexport ist noch nicht konfiguriert (wedding_date_iso fehlt).',
    declineConfirmTitle: 'Bist du sicher, dass du nicht kommst?',
    declineConfirmBody: 'Wir möchten nur kurz nachfragen — du kannst es später jederzeit ändern.',
    declineConfirmYes: 'Ja, ich bin sicher',
    declineConfirmBack: 'Zurück',
    declinedSadTitle: 'Schade, dass du nicht dabei bist 😢',
    declinedSadSub: 'Dein Wedding Pass ist gespeichert. Wenn sich etwas ändert, komm jederzeit zurück.',
    calendarEventTitle: 'Hochzeitsfeier',
    calendarEventDescription: 'Unser grosser Tag — Details in deinem Wedding Pass.',
    saveThisPageTitle: 'Tipp:',
    saveThisPageBody: 'Setze ein Lesezeichen, damit du jederzeit zurückkommst.',
    whyReturnTitle: 'Warum zurückkommen?',
    whyReturnBody: 'Wir aktualisieren diese Seite laufend mit allen Infos.',
    openFullInfo: 'Zur Infoseite',
    editAnswers: 'Antworten ändern',
    tabNeedToKnow: 'Alles Wichtige',
    tabVenue: 'Hochzeitslocation',
    tabDayItself: 'Der Tag',
    tabYourEvening: 'Dein Abend',
    comingSoon: 'Kommt bald',
    needToKnowTitle: 'Alles Wichtige',
    needToKnowBody: 'Ort, Anreise, Geschenke und Dresscode findest du hier.',
    giftDressCodeTitle: 'Geschenke & Dresscode',
    giftDressCodeBody: 'Die Details teilen wir hier näher am Datum.',
    dayItselfTitle: 'Ablauf',

    // Guest portal - timeline component
    timelineTitle: 'Hochzeitsablauf',
    timelineLoading: 'Ablauf wird geladen…',
    timelineEmpty: 'Noch keine Programmpunkte geplant.',
    dressCodeLabel: 'Dresscode:',
    
    // Guest portal - section labels
    venueLabel: 'Veranstaltungsort',
    dresscodeLabel: 'Dresscode',
    agendaLabel: 'Ablauf',

    // Guest portal - Gift Registry
    giftRegistryTitle: 'Geschenke',
    giftRegistryLoading: 'Geschenke werden geladen…',
    giftRegistryIntro:
      'Deine Anwesenheit ist das schönste Geschenk. Falls du uns trotzdem etwas schenken möchtest, findest du hier unsere Wunschlisten:',
    giftRegistryVisit: 'Zur Wunschliste',
    giftRegistryProgress: 'Fortschritt',
    giftRegistryCashHint: 'Beiträge können über den vom Paar bereitgestellten Link geleistet werden.',
    giftRegistryExperienceHint: 'Hilf uns, unvergessliche Erinnerungen zu schaffen!',
    giftRegistryEmpty: 'Noch keine Einträge vorhanden.',
    giftRegistryTypeExternal: 'Wunschlisten-Link',
    giftRegistryTypeCash: 'Geldgeschenk',
    giftRegistryTypeExperience: 'Erlebnis',
    giftRegistryTypeDefault: 'Geschenk',

    // Guest portal - Info page labels
    inviteTypeIndividual: 'Einzelperson',
    inviteTypeCouple: 'Paar',
    inviteTypeGroup: 'Gruppe',
    guestInfoTitle: 'Hochzeitsinfos',
    guestInfoSubtitle: 'Alles, was du wissen musst',
    guestInfoChangeTitle: 'Informationen ändern',
    guestInfoChangeBody: 'Du kannst deinen Wedding Pass jederzeit ansehen und ändern.',
    guestInfoChangeCardSubtitle: 'Wedding Pass ansehen und ändern',
    guestInfoCurrentAnswers: 'Deine aktuellen Antworten',
    guestInfoComing: 'Dabei',
    guestInfoAttending: 'Nimmst du an der Hochzeit teil?',
    guestInfoInviteType: 'Einladungsart',
    guestInfoGuests: 'Gäste',
    guestInfoOvernight: 'Übernachtung',
    bookingLinkHint: 'Buche mit unserem Sondertarif zu reduzierten Kosten.',
    bookingLinkClick: 'Hier klicken zum Buchen.',
    bookingLinkComingSoon: 'Buchungsinformationen folgen.',
    guestInfoDietary: 'Ernährung',
    guestInfoProvided: 'Vorhanden',
    guestInfoDietaryDetails: 'Details',
    guestInfoNotes: 'Notizen',
    guestInfoCancelEditing: 'Bearbeiten abbrechen',
    guestInfoEditHere: 'Hier bearbeiten',
    guestInfoOpenPass: 'Wedding Pass öffnen',
    guestInfoBackToInfo: 'Zurück zur Übersicht',
    guestInfoEditAnswers: 'Antworten bearbeiten',
    guestInfoWhoIsComing: 'Wer kommt mit?',
    guestInfoWhoIsComingHint: 'Bitte mindestens eine Person auswählen, wenn du kommst.',
    guestInfoDietaryRestrictions: 'Ernährungseinschränkungen',
    guestInfoSaveChanges: 'Änderungen speichern',

    // Guest portal - Travel & Accommodation
    guestTravelTitle: 'Anreise & Unterkunft',
    guestTravelCardSubtitle: 'Hotel und Wegbeschreibung',
    travelSectionTitle: 'Anreise',
    travelByCar: 'Mit dem Auto',
    travelByPublicTransport: 'Mit dem \u00d6V',
    travelCarDirections: 'Autobahnausfahrt A1 Lenzburg, Richtung Wohlen, Villmergen, Sarmenstorf, Meisterschwanden. Das Hotel befindet sich ausserhalb von Meisterschwanden, Richtung Aesch/Luzern.',
    travelCarTimes: 'Ab Z\u00fcrich 45 Minuten\nAb Bern 1 Stunde 20 Minuten\nAb Basel 1 Stunde\nAb Luzern 40 Minuten',
    travelCarParking: '500 Aussenparkpl\u00e4tze\n20 kostenpflichtige Tiefgaragenparkpl\u00e4tze inklusive 4 Ladestationen 22 kW Typ 2 Steckdose (Ladekosten nach Tarif)',
    travelCarParkingTitle: 'Parkpl\u00e4tze & E-Ladestationen',
    travelPublicTransportDirections: 'Von den Bahnh\u00f6fen Wohlen und Lenzburg besteht eine Postautoverbindung bis zur Haltestelle Meisterschwanden Oberdorf. Von dort werden unsere \u00dcbernachtungsg\u00e4ste kostenlos mit einem Shuttleservice abgeholt. Bitte gebt uns fr\u00fchzeitig eure genaue Ankunft bekannt.',
    travelNoteTitle: 'Wichtiger Hinweis zur Anreise',
    travelNoteBody: 'Am 10. Oktober 2026 findet rund um den Hallwilersee der Hallwilerseelauf statt. Die Zufahrt und Parkplätze der Seerose sind weiterhin uneingeschränkt nutzbar. Der Lauf führt jedoch durch das Hotel. Plant bitte genügend Zeit für die Anreise ein.',
    travelNoteLink: 'Mehr Infos',
    guestAccommodationVenueTitle: 'Unterkunft',
    guestAccommodationDetailsFallback: 'Unterkunftsdetails werden hier geteilt.',
    guestAccommodationOpenWebsite: 'Website öffnen',
    guestAccommodationBookingTitle: 'Zimmerreservierung',
    guestAccommodationBookNow: 'Zimmer buchen',
    guestAccommodationBookingStayTuned: 'Buchungsinformationen folgen',

    // Guest portal - Event & Gifts
    guestGiftsTitle: 'Event & Geschenke',
    guestGiftsCardSubtitle: 'Ablauf und Wunschliste',
    guestGiftsScheduleTitle: 'Ablauf',
    guestGiftsFeaturedEvent: 'Ausgewählter Programmpunkt',
    guestGiftsDetailsTitle: 'Details',

    // Guest portal - Gallery
    guestGalleryTitle: 'Fotogalerie',
    guestGalleryCardSubtitle: 'Teile deine Fotos',

    // Guest portal - Contact
    guestContactTitle: 'Kontakt',
    guestContactCardSubtitle: 'Schreib uns eine Nachricht',

    // Guest website top navigation
    guestNavHello: 'Hallo',
    guestNavWeddingPass: 'Wedding Pass',
    guestNavTravelAccommodation: 'Unterkunft & Anreise',
    guestNavWeddingProgram: 'Hochzeitsprogramm',
    guestNavGifts: 'Geschenke',
    guestNavPhotos: 'Fotos',
    guestNavContact: 'Kontakt',
    guestGiftsInfoTitle: 'Geschenke',
    guestGiftsInfoBody:
      'Deine Anwesenheit ist für uns das schönste Geschenk. Falls du trotzdem etwas schenken möchtest, findest du hier die Infos.',
    giftWishlistTitle: 'Was wir gerne erleben möchten',
    activitySkydiving: 'Fallschirmspringen',
    activityGolf: 'Golf',
    activityTheater: 'Theater',
    activityTennis: 'Tennis',
    activityDining: 'Fine Dining',
    giftIbanLabel: 'Banküberweisung',
    copied: 'Kopiert!',
    copyToClipboard: 'Kopieren',

    // Photo gallery
    photoGalleryTitle: 'Fotogalerie',
    photoGalleryLoading: 'Galerie wird geladen…',
    photoGallerySharedFolderTitle: 'Gemeinsamer Fotoordner',
    photoGalleryRedirecting: 'Weiterleitung zum gemeinsamen Ordner…',
    photoGalleryOpenFolder: 'Ordner öffnen',
    photoGalleryUploadToFolder: 'In Ordner hochladen',
    photoGalleryRedirectHint: 'Teile deine Fotos mit uns!',
    photoGalleryUploadTitle: 'Foto hochladen',
    photoGalleryCaptionPlaceholder: 'Bildunterschrift (optional)',
    photoGalleryUploading: 'Wird hochgeladen…',
    photoGalleryUploadButton: 'Foto hochladen',
    photoGalleryDropHint: 'Foto hierher ziehen oder antippen zum Auswählen',
    photoGallerySelectPhoto: 'Foto auswählen',
    photoGalleryUploadSuccess: 'Foto hochgeladen! Es wird nach Freigabe sichtbar.',
    photoGalleryUploadFailed: 'Foto-Upload fehlgeschlagen',
    photoGalleryInvalidFile: 'Bitte ein Bild auswählen',
    photoGalleryTooLarge: 'Bild darf maximal 10MB gross sein',

    // Contact form
    contactTitle: 'Kontakt',
    contactIntro: 'Hast du eine Frage? Schreib uns eine Nachricht und wir melden uns so schnell wie möglich.',
    contactSentTitle: 'Nachricht gesendet! Wir melden uns bald.',
    contactSendFailed: 'Nachricht konnte nicht gesendet werden',
    contactSubjectLabel: 'Betreff *',
    contactMessageLabel: 'Nachricht *',
    contactSubjectPlaceholder: 'z.B. Frage zur Unterkunft',
    contactMessagePlaceholder: 'Schreibe deine Nachricht…',
    contactSending: 'Wird gesendet…',
    contactSendButton: 'Nachricht senden',
    contactRetry: 'Erneut versuchen',

    // Contact toggle & witness cards
    contactBrideGroom: 'Brautpaar kontaktieren',
    contactWitnesses: 'Trauzeugen kontaktieren',
    witnessCardFlipHint: 'Tippen um Kontaktdaten zu sehen',
    witnessPhoneLabel: 'Telefon',

    // Guest login
    guestLoginTitle: 'Willkommen zurück',
    guestLoginSubtitle: 'Bitte melde dich an, um dein RSVP zu sehen',
    guestLoginUsername: 'Benutzername',
    guestLoginPassword: 'Passwort',
    guestLoginUsernamePlaceholder: 'Benutzername eingeben',
    guestLoginPasswordPlaceholder: 'Passwort eingeben',
    guestLoginSigningIn: 'Anmelden…',
    guestLoginSignIn: 'Anmelden',
    guestLoginFailed: 'Anmeldung fehlgeschlagen. Bitte prüfe deine Angaben.',

    // Guest registration
    guestRegisterInvalidInvitationTitle: 'Ungültige Einladung',
    guestRegisterInvalidInvitationBody: 'Kein Einladungs-Token gefunden. Bitte nutze den Link aus der Einladung.',
    guestRegisterGoToLogin: 'Zum Login',
    guestRegisterValidating: 'Einladung wird geprüft…',
    guestRegisterYoureInvited: 'Du bist eingeladen!',
    guestRegisterDearName: 'Liebe/r {{name}},',
    guestRegisterDearGuest: 'Liebe/r Gast,',
    guestRegisterHeroBody: 'Wir freuen uns riesig, diesen Tag mit dir zu feiern!',
    guestRegisterCompleteTitle: 'Registrierung abschliessen',
    guestRegisterCompleteSubtitle: 'Bitte fülle das Formular aus, um dein Konto zu erstellen und zuzusagen/abzusagen.',
    guestRegisterPlusOneLabel: 'Begleitung:',
    guestRegisterPlusOneBody: 'Du darfst {{count}} Person{{plural}} mitbringen',
    guestRegisterFirstName: 'Vorname *',
    guestRegisterLastName: 'Nachname *',
    guestRegisterPhone: 'Telefonnummer',
    guestRegisterPasswordHint: 'Mindestens 6 Zeichen',
    guestRegisterConfirmPassword: 'Passwort bestätigen *',
    guestRegisterCreatingAccount: 'Konto wird erstellt…',
    guestRegisterCreateContinue: 'Konto erstellen & weiter',
    guestRegisterPasswordsNoMatch: 'Passwörter stimmen nicht überein',
    guestRegisterPasswordTooShort: 'Passwort muss mindestens 6 Zeichen haben',
  },
  fr: {
    welcome: 'Bienvenue',
    rsvp: 'RSVP',
    hi: 'Salut',
    fillForm: 'Veuillez remplir le formulaire ci-dessous',
    introduction: "Nous sommes absolument ravis de célébrer ce jour spécial avec vous! Votre présence signifie tout pour nous, et nous avons hâte de partager ce beau moment ensemble. Veuillez prendre un moment pour remplir le formulaire ci-dessous afin que nous puissions nous assurer que tout est parfait pour votre visite. Nous avons inclus des sections pour les préférences alimentaires, les demandes musicales et tout hébergement spécial dont vous pourriez avoir besoin. N'hésitez pas à nous contacter si vous avez des questions. Nous avons hâte de vous voir bientôt!",
    rsvpDetails: 'Détails RSVP',
    overnightStay: 'Hébergement',
    overnightStayQuestion: 'Souhaitez-vous rester pour la nuit?',
    overnightStayYes: 'Oui, je souhaite rester pour la nuit',
    overnightStayNo: 'Non, je ne souhaite pas rester pour la nuit',
    overnightStayNote: "Vous devez organiser l\'hébergement vous-mêmes.",
    select: 'Sélectionner...',
    numberOfGuests: "Nombre d\'invités",
    rsvpStatus: 'Statut RSVP',
    pending: 'En attente',
    confirmed: 'Confirmé',
    declined: 'Refusé',
    contactInfo: 'Informations de contact',
    phone: 'Téléphone',
    address: 'Adresse',
    musicWish: 'Souhait musical',
    songRequests: 'Demandes de chansons',
    musicPlaceholder: 'Quelles chansons aimeriez-vous entendre au mariage?',
    dietaryInfo: 'Informations diététiques',
    dietaryRestrictions: 'Restrictions alimentaires',
    dietaryPlaceholder: 'par ex. Végétarien, Végétalien, Sans gluten',
    allergies: 'Allergies',
    allergiesPlaceholder: 'Veuillez lister toutes les allergies alimentaires',
    specialRequests: 'Demandes spéciales',
    specialPlaceholder: 'Toute demande spéciale ou information supplémentaire',
    submitRSVP: 'Soumettre RSVP',
    saving: 'Enregistrement...',
    ourStory: 'Notre histoire',
    invalidLink: 'Lien RSVP invalide',
    invalidLinkMessage: "Ce lien RSVP n\'est pas valide. Veuillez vérifier le lien et réessayer.",
    loadingRSVP: 'Chargement de votre RSVP...',
    confirmAttendance: 'Veuillez confirmer votre présence',

    // Guest Journey / Wedding Pass
    yourWeddingPass: 'Votre Pass Mariage',
    yourInvitation: 'Votre invitation',
    joinOurCelebration: 'Célébrez avec nous',
    passIntro: 'Un compagnon de mariage auquel vous pouvez revenir à tout moment.',
    loadingWeddingPass: 'Chargement de votre Pass Mariage...',
    invalidInvitationLinkTitle: 'Lien d’invitation invalide',
    invalidInvitationLinkMessage: 'Ce lien d’invitation n’est pas valide. Veuillez vérifier le lien et réessayer.',
    invalidInvitationContactHint: 'Si vous pensez qu\'il s\'agit d\'une erreur, veuillez contacter les mariés pour obtenir un nouveau lien d\'invitation.',
    authFailed: 'Échec de l’authentification',
    authMissing: 'Aucun jeton d’authentification disponible',
    saveFailed: 'Impossible d’enregistrer votre réponse. Veuillez réessayer.',
    stepLabel: 'Étape',
    statusPending: 'Pas encore décidé',
    statusYes: 'Présent',
    statusNo: 'Absent',
    yes: 'Oui',
    no: 'Non',
    back: 'Retour',
    next: 'Suivant',
    continue: 'Continuer',
    skipForNow: 'Plus tard',
    changeToNo: 'Non, finalement',
    youCanEditAnytime: "Tu pourras modifier tes r\u00e9ponses jusqu'au 30 avril 2026.",
    youCanEditAnytime_plural: "Vous pourrez modifier vos r\u00e9ponses jusqu'au 30 avril 2026.",
    rsvpDeadlinePassed: "La date limite de r\u00e9ponse (30 avril 2026) est pass\u00e9e. Les modifications ne sont plus possibles.",
    rsvpDeadlinePassedSub: "Si vous avez besoin de faire des changements, veuillez contacter directement les mari\u00e9s.",
    rsvpCurrentStatus: 'Votre statut RSVP actuel :',
    contactCoupleFlipHint: 'Appuyez pour voir les coordonn\u00e9es',
    contactCoupleDescription: "Votre bien-\u00eatre nous tient tr\u00e8s \u00e0 c\u0153ur. S'il y a quoi que ce soit que vous aimeriez clarifier en lien avec notre mariage \u2014 des d\u00e9tails organisationnels aux questions personnelles \u2014 n'h\u00e9sitez pas \u00e0 nous contacter \u00e0 tout moment. C'est avec plaisir que nous sommes l\u00e0 pour vous.",
    contactWitnessesDescription: "Pour des id\u00e9es autour du programme du mariage, des surprises, des discours, des jeux ou des contributions sp\u00e9ciales, adressez-vous \u00e0 nos merveilleux t\u00e9moins. Ils se r\u00e9jouissent de vos id\u00e9es cr\u00e9atives et aident avec beaucoup de c\u0153ur \u00e0 la coordination.",
    ourBigDay: 'notre grand jour',
    attendanceVenueHint: 'Seerose Resort & Spa, Hallwilersee',
    doneOvernightHint: "Si vous souhaitez passer la nuit, utilisez le code de r\u00e9servation pour le Seerose Resort & Spa. Tous les d\u00e9tails se trouvent dans la section H\u00e9bergement & Voyage.",
    qCelebrateOnDate: 'Célébreras-tu notre mariage avec nous le {{date}} ?',
    qCelebrateOnDate_plural: 'Célébrerez-vous notre mariage avec nous le {{date}} ?',
    qCelebrateSub: 'Un simple clic — on s’occupe du reste.',
    qBothComing: 'Venez-vous tous les deux ?',
    qBothComingSub: 'Pour nous aider à organiser les places et le menu.',
    bothOfUs: 'Oui, tous les deux',
    justMe: 'Seulement moi',
    onlyName: 'Seulement {{name}}',
    name1: 'Nom 1',
    name2: 'Nom 2',
    qGroupHowMany: 'Combien serez-vous à venir ?',
    qGroupHowManySub: 'Jusqu’à {{max}} invités — combien devons-nous prévoir ?',
    groupMaxNote: 'Invités max : {{max}}',
    people: 'personnes',
    qGroupWhoComing: 'Qui viendra ?',
    qGroupWhoComingSub: 'Sélectionnez toutes les personnes présentes.',
    selectedCount: '{{count}} sur {{max}} sélectionnés',
    qOvernight: 'Resteras-tu pour la nuit ?',
    qOvernight_plural: 'Resterez-vous pour la nuit ?',
    qOvernightSub: 'Cela nous aide pour l’organisation.',
    overnightNoteSoft: 'L’hébergement est organisé individuellement.',
    overnightAccommodationHint: "Vous trouverez plus de détails dans la section Hébergement & Voyage sur la page du mariage.",
    qDietary: 'As-tu des restrictions alimentaires ?',
    qDietary_plural: 'Avez-vous des restrictions alimentaires ?',
    qDietarySub: 'Une petite note suffit.',
    dietaryPlaceholderShort: 'ex. végétarien, sans gluten, pas de noix…',
    qNotes: "As-tu un souhait musical ou d'autres demandes ?",
    qNotes_plural: "Avez-vous un souhait musical ou d'autres demandes ?",
    qNotesSub: 'Optionnel — dites-nous ce qui rendrait votre expérience spéciale.',
    notesPlaceholder: 'ex. chanson préférée, préférence de place…',
    finish: 'Terminer',
    qAddPhoto: "Envie d'ajouter une photo ?",
    qAddPhotoSub: 'Optionnel — elle apparaîtra dans la galerie après validation.',
    photoOptional: 'Totalement optionnel. Vous pourrez le faire plus tard.',
    photoCaptionPlaceholder: 'Légende (optionnel)',
    uploadAndContinue: 'Téléverser & continuer',
    photoUploaded: 'Photo téléversée (en attente de validation).',
    photoUploadFailed: 'Échec du téléversement. Veuillez réessayer.',
    doneTitle: 'Tout est prêt',
    doneSub: 'Merci — votre Pass Mariage est enregistré.',
    doneYesTitle: 'Nous sommes si heureux de vous compter parmi nous',
    doneYesSub: 'Votre Pass Mariage est enregistré — à très vite.',
    doneNoTitle: 'Merci de nous avoir prévenus',
    doneNoSub: 'Votre Pass Mariage est enregistré. Vous pouvez consulter les détails ci-dessous.',
    addToCalendar: 'Ajouter au calendrier',
    saveThisPageButton: 'Enregistrer cette page',
    savePageTitle: 'Enregistrer cette page',
    savePageInstall: 'Installer / Ajouter à l\'écran d\'accueil',
    savePageInstructions: 'Mettez en favori (Ctrl/Cmd + D) ou utilisez l\'étoile dans le navigateur.',
    savePageInstructions_ios: 'Appuyez sur Partager, puis "Sur l\'écran d\'accueil" ou favori.',
    savePageInstructions_android: 'Appuyez sur Menu (⋮), puis "Ajouter à l\'écran d\'accueil" ou "Installer".',
    savePageInstructions_desktop: 'Appuyez sur Ctrl/Cmd + D pour mettre en favori, ou l\'étoile dans la barre d\'adresse.',
    savePageCopyLink: 'Copier le lien',
    savePageCopied: 'Copié !',
    savePageHint: 'Veuillez mettre cette page en favori (Ctrl/Cmd + D).',
    calendarNotConfigured: 'Export calendrier non configuré (wedding_date_iso manquant).',
    declineConfirmTitle: 'Êtes-vous sûr de ne pas venir ?',
    declineConfirmBody: 'On veut juste confirmer — vous pourrez toujours changer plus tard.',
    declineConfirmYes: 'Oui, je suis sûr',
    declineConfirmBack: 'Retour',
    declinedSadTitle: 'Triste de vous voir partir 😢',
    declinedSadSub: 'Votre Pass Mariage est enregistré. Si ça change, revenez quand vous voulez.',
    calendarEventTitle: 'Célébration de mariage',
    calendarEventDescription: 'Notre grand jour — détails dans votre Pass Mariage.',
    saveThisPageTitle: 'Astuce :',
    saveThisPageBody: 'Ajoutez cette page en favori pour y revenir facilement.',
    whyReturnTitle: 'Pourquoi revenir ?',
    whyReturnBody: 'Nous mettrons cette page à jour avec toutes les infos utiles.',
    openFullInfo: 'Ouvrir la page d’infos',
    editAnswers: 'Modifier mes réponses',
    tabNeedToKnow: 'À savoir',
    tabVenue: 'Lieu',
    tabDayItself: 'Le jour J',
    tabYourEvening: 'Votre soirée',
    comingSoon: 'Bientôt disponible',
    needToKnowTitle: 'À savoir',
    needToKnowBody: 'Lieu, voyage, cadeaux et tenue seront ici.',
    giftDressCodeTitle: 'Cadeaux & tenue',
    giftDressCodeBody: 'Nous partagerons les détails à l’approche du jour J.',
    dayItselfTitle: 'Planning',

    // Guest portal - timeline component
    timelineTitle: 'Planning du mariage',
    timelineLoading: 'Chargement du planning…',
    timelineEmpty: 'Aucun événement prévu pour le moment.',
    dressCodeLabel: 'Tenue :',
    
    // Guest portal - section labels
    venueLabel: 'Lieu',
    dresscodeLabel: 'Tenue',
    agendaLabel: 'Programme',

    // Guest portal - Gift Registry
    giftRegistryTitle: 'Liste de cadeaux',
    giftRegistryLoading: 'Chargement de la liste…',
    giftRegistryIntro:
      'Votre présence est le plus beau des cadeaux. Si vous souhaitez toutefois nous offrir quelque chose, voici nos listes :',
    giftRegistryVisit: 'Voir la liste',
    giftRegistryProgress: 'Progression',
    giftRegistryCashHint: 'Les contributions peuvent être faites via le lien fourni par le couple.',
    giftRegistryExperienceHint: 'Aidez-nous à créer des souvenirs inoubliables !',
    giftRegistryEmpty: 'Aucun élément disponible pour le moment.',
    giftRegistryTypeExternal: 'Lien de liste',
    giftRegistryTypeCash: 'Cagnotte',
    giftRegistryTypeExperience: 'Expérience',
    giftRegistryTypeDefault: 'Cadeau',

    // Guest portal - Info page labels
    inviteTypeIndividual: 'Individuel',
    inviteTypeCouple: 'Couple',
    inviteTypeGroup: 'Groupe',
    guestInfoTitle: 'Infos mariage',
    guestInfoSubtitle: 'Tout ce que vous devez savoir',
    guestInfoChangeTitle: 'Modifier vos informations',
    guestInfoChangeBody: 'Vous pouvez consulter et modifier votre Pass Mariage à tout moment.',
    guestInfoChangeCardSubtitle: 'Consulter et modifier votre Pass',
    guestInfoCurrentAnswers: 'Vos réponses actuelles',
    guestInfoComing: 'Présence',
    guestInfoInviteType: 'Type d’invitation',
    guestInfoAttending: 'Serez-vous présent au mariage ?',
    guestInfoGuests: 'Invités',
    guestInfoOvernight: 'Hébergement',
    bookingLinkHint: 'Réservez avec notre tarif spécial pour un prix réduit.',
    bookingLinkClick: 'Cliquez ici pour réserver.',
    bookingLinkComingSoon: 'Informations de réservation à venir.',
    guestInfoDietary: 'Alimentation',
    guestInfoProvided: 'Renseigné',
    guestInfoDietaryDetails: 'Détails',
    guestInfoNotes: 'Notes',
    guestInfoCancelEditing: 'Annuler',
    guestInfoEditHere: 'Modifier ici',
    guestInfoOpenPass: 'Ouvrir votre Pass Mariage',
    guestInfoBackToInfo: 'Retour aux infos',
    guestInfoEditAnswers: 'Modifier vos réponses',
    guestInfoWhoIsComing: 'Qui vient ?',
    guestInfoWhoIsComingHint: 'Laissez au moins une personne sélectionnée si vous venez.',
    guestInfoDietaryRestrictions: 'Restrictions alimentaires',
    guestInfoSaveChanges: 'Enregistrer',

    // Guest portal - Travel & Accommodation
    guestTravelTitle: 'Voyage & hébergement',
    guestTravelCardSubtitle: 'Hôtel et itinéraire',
    travelSectionTitle: 'Comment venir',
    travelByCar: 'En voiture',
    travelByPublicTransport: 'En transports publics',
    travelCarDirections: "Sortie autoroute A1 Lenzburg, direction Wohlen, Villmergen, Sarmenstorf, Meisterschwanden. L'h\u00f4tel se trouve \u00e0 l'ext\u00e9rieur de Meisterschwanden, direction Aesch/Lucerne.",
    travelCarTimes: 'Depuis Zurich 45 minutes\nDepuis Berne 1 heure 20 minutes\nDepuis B\u00e2le 1 heure\nDepuis Lucerne 40 minutes',
    travelCarParking: "500 places de parking ext\u00e9rieures\n20 places de parking souterrain payantes dont 4 bornes de recharge 22 kW prise Type 2 (frais de recharge selon tarif)",
    travelCarParkingTitle: 'Parking & bornes de recharge',
    travelPublicTransportDirections: "Depuis les gares de Wohlen et Lenzburg, une liaison CarPostal dessert l'arr\u00eat Meisterschwanden Oberdorf. De l\u00e0, nos h\u00f4tes passant la nuit seront r\u00e9cup\u00e9r\u00e9s gratuitement par un service de navette. Merci de nous communiquer votre heure d'arriv\u00e9e exacte \u00e0 l'avance.",
    travelNoteTitle: 'Information importante pour le trajet',
    travelNoteBody: "Le 10 octobre 2026, la course Hallwilerseelauf aura lieu autour du lac de Hallwil. Les accès et parkings du Seerose restent entièrement disponibles. Cependant, le parcours de la course traverse l'hôtel. Veuillez prévoir un temps de trajet supplémentaire.",
    travelNoteLink: "Plus d'infos",
    guestAccommodationVenueTitle: 'Hébergement',
    guestAccommodationDetailsFallback: 'Les informations d’hébergement seront indiquées ici.',
    guestAccommodationOpenWebsite: 'Ouvrir le site',
    guestAccommodationBookingTitle: 'Réservation de chambre',
    guestAccommodationBookNow: 'Réserver une chambre',
    guestAccommodationBookingStayTuned: 'Informations de réservation à venir',

    // Guest portal - Event & Gifts
    guestGiftsTitle: 'Événement & cadeaux',
    guestGiftsCardSubtitle: 'Planning et liste',
    guestGiftsScheduleTitle: 'Planning',
    guestGiftsFeaturedEvent: 'Élément sélectionné',
    guestGiftsDetailsTitle: 'Détails',

    // Guest portal - Gallery
    guestGalleryTitle: 'Galerie photo',
    guestGalleryCardSubtitle: 'Partagez vos photos',

    // Guest portal - Contact
    guestContactTitle: 'Contact',
    guestContactCardSubtitle: 'Envoyez-nous un message',

    // Guest website top navigation
    guestNavHello: 'Salut',
    guestNavWeddingPass: 'Pass Mariage',
    guestNavTravelAccommodation: 'Hébergement & Voyage',
    guestNavWeddingProgram: 'Programme du mariage',
    guestNavGifts: 'Cadeaux',
    guestNavPhotos: 'Photos',
    guestNavContact: 'Contact',
    guestGiftsInfoTitle: 'Cadeaux',
    guestGiftsInfoBody:
      'Votre présence est le plus beau des cadeaux. Si vous souhaitez offrir quelque chose, vous trouverez les informations ici.',
    giftWishlistTitle: 'Ce que nous aimerions faire',
    activitySkydiving: 'Parachutisme',
    activityGolf: 'Golf',
    activityTheater: 'Théâtre',
    activityTennis: 'Tennis',
    activityDining: 'Gastronomie',
    giftIbanLabel: 'Virement bancaire',
    copied: 'Copié !',
    copyToClipboard: 'Copier',

    // Photo gallery
    photoGalleryTitle: 'Galerie photo',
    photoGalleryLoading: 'Chargement de la galerie…',
    photoGallerySharedFolderTitle: 'Dossier photo partagé',
    photoGalleryRedirecting: 'Redirection vers le dossier partagé…',
    photoGalleryOpenFolder: 'Ouvrir le dossier',
    photoGalleryUploadToFolder: 'Téléverser dans le dossier',
    photoGalleryRedirectHint: 'Partagez vos photos avec nous !',
    photoGalleryUploadTitle: 'Téléverser une photo',
    photoGalleryCaptionPlaceholder: 'Légende (optionnel)',
    photoGalleryUploading: 'Téléversement…',
    photoGalleryUploadButton: 'Téléverser la photo',
    photoGalleryDropHint: 'Glissez-déposez une photo ici, ou appuyez pour choisir',
    photoGallerySelectPhoto: 'Choisir une photo',
    photoGalleryUploadSuccess: 'Photo téléversée ! Elle sera visible après validation.',
    photoGalleryUploadFailed: 'Échec du téléversement',
    photoGalleryInvalidFile: 'Veuillez choisir un fichier image',
    photoGalleryTooLarge: 'La photo doit faire moins de 10MB',

    // Contact form
    contactTitle: 'Contact',
    contactIntro: 'Une question ? Envoyez-nous un message et nous vous répondrons rapidement.',
    contactSentTitle: 'Message envoyé ! Nous vous répondrons bientôt.',
    contactSendFailed: 'Échec de l’envoi du message',
    contactSubjectLabel: 'Sujet *',
    contactMessageLabel: 'Message *',
    contactSubjectPlaceholder: 'ex. Question sur l’hébergement',
    contactMessagePlaceholder: 'Écrivez votre message…',
    contactSending: 'Envoi…',
    contactSendButton: 'Envoyer',
    contactRetry: 'Réessayer',

    // Contact toggle & witness cards
    contactBrideGroom: 'Contacter les mariés',
    contactWitnesses: 'Contacter les témoins',
    witnessCardFlipHint: 'Appuyez pour voir les coordonnées',
    witnessPhoneLabel: 'Téléphone',

    // Guest login
    guestLoginTitle: 'Content de vous revoir',
    guestLoginSubtitle: 'Connectez-vous pour accéder à votre RSVP',
    guestLoginUsername: "Nom d’utilisateur",
    guestLoginPassword: 'Mot de passe',
    guestLoginUsernamePlaceholder: "Saisissez votre nom d’utilisateur",
    guestLoginPasswordPlaceholder: 'Saisissez votre mot de passe',
    guestLoginSigningIn: 'Connexion…',
    guestLoginSignIn: 'Se connecter',
    guestLoginFailed: 'Connexion impossible. Vérifiez vos identifiants.',

    // Guest registration
    guestRegisterInvalidInvitationTitle: 'Invitation invalide',
    guestRegisterInvalidInvitationBody: "Aucun jeton d’invitation trouvé. Veuillez utiliser le lien de l’invitation.",
    guestRegisterGoToLogin: 'Aller au login',
    guestRegisterValidating: 'Vérification de l’invitation…',
    guestRegisterYoureInvited: 'Vous êtes invité(e) !',
    guestRegisterDearName: 'Cher/Chère {{name}},',
    guestRegisterDearGuest: 'Cher/Chère invité(e),',
    guestRegisterHeroBody: 'Nous sommes ravis de vous inviter à célébrer ce jour avec nous !',
    guestRegisterCompleteTitle: 'Finaliser votre inscription',
    guestRegisterCompleteSubtitle: 'Remplissez le formulaire pour créer votre compte et répondre au RSVP',
    guestRegisterPlusOneLabel: 'Accompagnant :',
    guestRegisterPlusOneBody: 'Vous pouvez venir avec {{count}} invité{{plural}}',
    guestRegisterFirstName: 'Prénom *',
    guestRegisterLastName: 'Nom *',
    guestRegisterPhone: 'Téléphone',
    guestRegisterPasswordHint: 'Au moins 6 caractères',
    guestRegisterConfirmPassword: 'Confirmer le mot de passe *',
    guestRegisterCreatingAccount: 'Création du compte…',
    guestRegisterCreateContinue: 'Créer le compte & continuer',
    guestRegisterPasswordsNoMatch: 'Les mots de passe ne correspondent pas',
    guestRegisterPasswordTooShort: 'Le mot de passe doit contenir au moins 6 caractères',
  },
}

export function LanguageProvider({ children, initialLanguage = 'en' }) {
  const [language, setLanguage] = useState(() => {
    // Try to get from localStorage or use initial language
    const saved = localStorage.getItem('guest_language')
    return saved || initialLanguage
  })

  // Fetch content from database
  const { data: contentItems } = useQuery({
    queryKey: ['content', 'public', language],
    queryFn: () => api.get(`/content?lang=${language}`).then((res) => res.data),
    enabled: true, // Always fetch
  })

  useEffect(() => {
    localStorage.setItem('guest_language', language)
  }, [language])

  const t = (key) => {
    // First try to get from database content
    if (contentItems) {
      const contentItem = contentItems.find(item => item.key === key)
      if (contentItem && contentItem.content) {
        return contentItem.content
      }
    }
    
    // Fallback to hardcoded translations
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

