-- Wedding Planner D1 Schema
-- SQLite-compatible, Cloudflare D1
-- All IDs: TEXT UUID generated by Python (str(uuid.uuid4()))

-- Users (admin/couple accounts)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  is_active INTEGER NOT NULL DEFAULT 1,
  email_verified INTEGER NOT NULL DEFAULT 0,
  email_verified_at TEXT,
  current_wedding_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Email verification tokens (24-hour expiry)
CREATE TABLE IF NOT EXISTS email_verifications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_email_verifications_token ON email_verifications(token);
CREATE INDEX IF NOT EXISTS idx_email_verifications_user ON email_verifications(user_id);

-- Weddings (multi-tenant root)
CREATE TABLE IF NOT EXISTS weddings (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  owner_id TEXT NOT NULL,
  partner_one_name TEXT,
  partner_two_name TEXT,
  wedding_date TEXT,
  location TEXT,
  plan TEXT NOT NULL DEFAULT 'free',
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_weddings_slug ON weddings(slug);
CREATE INDEX IF NOT EXISTS idx_weddings_owner ON weddings(owner_id);
CREATE INDEX IF NOT EXISTS idx_weddings_stripe_customer ON weddings(stripe_customer_id);

-- Guests
CREATE TABLE IF NOT EXISTS guests (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  unique_token TEXT UNIQUE NOT NULL,
  username TEXT,
  rsvp_status TEXT NOT NULL DEFAULT 'pending',
  overnight_stay INTEGER NOT NULL DEFAULT 0,
  number_of_guests INTEGER NOT NULL DEFAULT 1,
  invitee_names TEXT,
  attending_names TEXT,
  dietary_restrictions TEXT,
  allergies TEXT,
  special_requests TEXT,
  music_wish TEXT,
  address TEXT,
  notes TEXT,
  language TEXT NOT NULL DEFAULT 'en',
  registered_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_accessed TEXT,
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_guests_wedding ON guests(wedding_id);
CREATE INDEX IF NOT EXISTS idx_guests_token ON guests(unique_token);
CREATE INDEX IF NOT EXISTS idx_guests_email ON guests(email);

-- Tasks
CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'todo',
  due_date TEXT,
  category TEXT,
  assigned_to TEXT,
  estimated_cost REAL,
  actual_cost REAL,
  event_id TEXT,
  completed_at TEXT,
  reminder_date TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_wedding ON tasks(wedding_id);

-- Costs / Budget
CREATE TABLE IF NOT EXISTS costs (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'CHF',
  status TEXT NOT NULL DEFAULT 'planned',
  payment_date TEXT,
  vendor_name TEXT,
  vendor_contact TEXT,
  receipt_url TEXT,
  vendor TEXT,
  notes TEXT,
  is_recurring INTEGER NOT NULL DEFAULT 0,
  recurring_frequency TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_costs_wedding ON costs(wedding_id);

-- CMS Content (global, not per-wedding)
CREATE TABLE IF NOT EXISTS content (
  id TEXT PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  title TEXT,
  content TEXT,
  content_en TEXT,
  content_de TEXT,
  content_fr TEXT,
  content_type TEXT NOT NULL DEFAULT 'html',
  is_public INTEGER NOT NULL DEFAULT 1,
  "order" INTEGER NOT NULL DEFAULT 0,
  published_at TEXT,
  scheduled_publish_at TEXT,
  scheduled_unpublish_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Wedding Public Page Content (per-wedding)
CREATE TABLE IF NOT EXISTS wedding_content (
  id TEXT PRIMARY KEY,
  wedding_id TEXT UNIQUE NOT NULL,
  couple_names TEXT,
  wedding_date TEXT,
  venue TEXT,
  message TEXT,
  faq TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- AI Usage Tracking
CREATE TABLE IF NOT EXISTS ai_usage (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  used_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_wedding ON ai_usage(wedding_id);

-- Events (wedding events / sub-events)
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  user_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  location TEXT,
  start_time TEXT,
  end_time TEXT,
  is_public INTEGER NOT NULL DEFAULT 1,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_events_wedding ON events(wedding_id);

-- Invitations
CREATE TABLE IF NOT EXISTS invitations (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  template_id TEXT,
  token TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  sent_at TEXT,
  opened_at TEXT,
  scheduled_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE INDEX IF NOT EXISTS idx_invitations_wedding ON invitations(wedding_id);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);

-- Invitation Templates
CREATE TABLE IF NOT EXISTS invitation_templates (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Messages (guest ↔ couple messaging)
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  content TEXT NOT NULL,
  sender_type TEXT NOT NULL DEFAULT 'guest',
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_messages_wedding ON messages(wedding_id);

-- Gift Registry
CREATE TABLE IF NOT EXISTS gift_registry (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price REAL,
  url TEXT,
  image_url TEXT,
  is_purchased INTEGER NOT NULL DEFAULT 0,
  purchased_by TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_gift_registry_wedding ON gift_registry(wedding_id);

-- Guest Photos
CREATE TABLE IF NOT EXISTS guest_photos (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  file_url TEXT NOT NULL,
  caption TEXT,
  is_approved INTEGER NOT NULL DEFAULT 0,
  uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE INDEX IF NOT EXISTS idx_guest_photos_wedding ON guest_photos(wedding_id);

-- Images (general wedding images)
CREATE TABLE IF NOT EXISTS images (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  filename TEXT NOT NULL,
  original_filename TEXT,
  file_url TEXT NOT NULL,
  mime_type TEXT,
  size INTEGER,
  category TEXT,
  is_public INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_images_wedding ON images(wedding_id);

-- Venues
CREATE TABLE IF NOT EXISTS venues (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  location TEXT,
  address TEXT,
  capacity INTEGER,
  price_per_day REAL,
  website TEXT,
  phone TEXT,
  email TEXT,
  images TEXT,
  amenities TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Venue Requests (couple ↔ venue enquiries)
CREATE TABLE IF NOT EXISTS venue_requests (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  message TEXT,
  response TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- Venue Offer Categories
CREATE TABLE IF NOT EXISTS venue_offer_categories (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Offers
CREATE TABLE IF NOT EXISTS venue_offers (
  id TEXT PRIMARY KEY,
  category_id TEXT NOT NULL,
  venue_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  price REAL,
  unit TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (category_id) REFERENCES venue_offer_categories(id),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Documents
CREATE TABLE IF NOT EXISTS venue_documents (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  filename TEXT NOT NULL,
  file_url TEXT NOT NULL,
  doc_type TEXT,
  content_text TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Chat History (AI-assisted venue enquiries)
CREATE TABLE IF NOT EXISTS venue_chat_history (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  wedding_id TEXT,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Seating Tables
CREATE TABLE IF NOT EXISTS seating_tables (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 10,
  shape TEXT NOT NULL DEFAULT 'round',
  x REAL,
  y REAL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_seating_tables_wedding ON seating_tables(wedding_id);

-- Seat Assignments
CREATE TABLE IF NOT EXISTS seat_assignments (
  id TEXT PRIMARY KEY,
  table_id TEXT NOT NULL,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  seat_number INTEGER,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (table_id) REFERENCES seating_tables(id),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

-- RSVP Reminders
CREATE TABLE IF NOT EXISTS rsvp_reminders (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  send_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  target_rsvp_status TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- Reminder Sent Records
CREATE TABLE IF NOT EXISTS reminder_sent (
  id TEXT PRIMARY KEY,
  reminder_id TEXT NOT NULL,
  guest_id TEXT NOT NULL,
  sent_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (reminder_id) REFERENCES rsvp_reminders(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

-- Moodboards
CREATE TABLE IF NOT EXISTS moodboards (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  user_id TEXT,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Moodboard Elements
CREATE TABLE IF NOT EXISTS moodboard_elements (
  id TEXT PRIMARY KEY,
  moodboard_id TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT,
  x REAL,
  y REAL,
  width REAL,
  height REAL,
  rotation REAL DEFAULT 0,
  z_index INTEGER DEFAULT 0,
  properties TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (moodboard_id) REFERENCES moodboards(id)
);

-- Agenda Items (wedding day schedule)
CREATE TABLE IF NOT EXISTS agenda_items (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  start_time TEXT NOT NULL,
  end_time TEXT,
  location TEXT,
  responsible_person TEXT,
  "order" INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_agenda_items_wedding ON agenda_items(wedding_id);

-- User Subscriptions (token billing)
CREATE TABLE IF NOT EXISTS user_subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  plan TEXT NOT NULL DEFAULT 'free',
  balance_tokens INTEGER NOT NULL DEFAULT 0,
  total_purchased INTEGER NOT NULL DEFAULT 0,
  total_consumed INTEGER NOT NULL DEFAULT 0,
  stripe_subscription_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Token Usage
CREATE TABLE IF NOT EXISTS token_usage (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  action TEXT NOT NULL,
  tokens_consumed INTEGER NOT NULL DEFAULT 0,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Analytics: Page Views
CREATE TABLE IF NOT EXISTS page_views (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  path TEXT NOT NULL,
  referrer TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_page_views_wedding ON page_views(wedding_id);

-- Analytics: Visits (sessions)
CREATE TABLE IF NOT EXISTS visits (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  session_id TEXT,
  started_at TEXT NOT NULL DEFAULT (datetime('now')),
  ended_at TEXT,
  page_count INTEGER DEFAULT 1
);

-- Analytics: Security Events
CREATE TABLE IF NOT EXISTS security_events (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  user_id TEXT,
  details TEXT,
  severity TEXT NOT NULL DEFAULT 'low',
  ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
