-- Wedding Planner D1 Schema
-- SQLite-compatible, Cloudflare D1
-- All IDs: TEXT UUID generated by Python (str(uuid.uuid4()))

-- Users (admin/couple accounts)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  is_active INTEGER NOT NULL DEFAULT 1,
  email_verified INTEGER NOT NULL DEFAULT 0,
  email_verified_at TEXT,
  current_wedding_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Email verification tokens (24-hour expiry)
CREATE TABLE IF NOT EXISTS email_verifications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_email_verifications_token ON email_verifications(token);
CREATE INDEX IF NOT EXISTS idx_email_verifications_user ON email_verifications(user_id);

-- Password reset tokens (1-hour expiry, single use)
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user ON password_reset_tokens(user_id);

-- Weddings (multi-tenant root)
CREATE TABLE IF NOT EXISTS weddings (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  owner_id TEXT NOT NULL,
  partner_one_name TEXT,
  partner_two_name TEXT,
  wedding_date TEXT,
  location TEXT,
  plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'premium', 'lifetime')),
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  plan_expires_at TEXT,
  plan_updated_at TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_weddings_slug ON weddings(slug);
CREATE INDEX IF NOT EXISTS idx_weddings_owner ON weddings(owner_id);
CREATE INDEX IF NOT EXISTS idx_weddings_stripe_customer ON weddings(stripe_customer_id);

-- Guests
CREATE TABLE IF NOT EXISTS guests (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  unique_token TEXT UNIQUE NOT NULL,
  username TEXT,
  rsvp_status TEXT NOT NULL DEFAULT 'pending',
  overnight_stay INTEGER NOT NULL DEFAULT 0,
  number_of_guests INTEGER NOT NULL DEFAULT 1,
  invitee_names TEXT,
  attending_names TEXT,
  dietary_restrictions TEXT,
  allergies TEXT,
  special_requests TEXT,
  music_wish TEXT,
  address TEXT,
  notes TEXT,
  language TEXT NOT NULL DEFAULT 'en',
  registered_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_accessed TEXT,
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_guests_wedding ON guests(wedding_id);
CREATE INDEX IF NOT EXISTS idx_guests_token ON guests(unique_token);
CREATE INDEX IF NOT EXISTS idx_guests_email ON guests(email);

-- Tasks
CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'todo',
  due_date TEXT,
  category TEXT,
  assigned_to TEXT,
  estimated_cost REAL,
  actual_cost REAL,
  event_id TEXT,
  completed_at TEXT,
  reminder_date TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_wedding ON tasks(wedding_id);

-- Costs / Budget
CREATE TABLE IF NOT EXISTS costs (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'CHF',
  status TEXT NOT NULL DEFAULT 'planned',
  payment_date TEXT,
  vendor_name TEXT,
  vendor_contact TEXT,
  receipt_url TEXT,
  vendor TEXT,
  notes TEXT,
  is_recurring INTEGER NOT NULL DEFAULT 0,
  recurring_frequency TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_costs_wedding ON costs(wedding_id);

-- CMS Content (global, not per-wedding)
CREATE TABLE IF NOT EXISTS content (
  id TEXT PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  title TEXT,
  content TEXT,
  content_en TEXT,
  content_de TEXT,
  content_fr TEXT,
  content_type TEXT NOT NULL DEFAULT 'html',
  is_public INTEGER NOT NULL DEFAULT 1,
  "order" INTEGER NOT NULL DEFAULT 0,
  published_at TEXT,
  scheduled_publish_at TEXT,
  scheduled_unpublish_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Wedding Public Page Content (per-wedding)
CREATE TABLE IF NOT EXISTS wedding_content (
  id TEXT PRIMARY KEY,
  wedding_id TEXT UNIQUE NOT NULL,
  couple_names TEXT,
  wedding_date TEXT,
  venue TEXT,
  message TEXT,
  faq TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- AI Usage Tracking
CREATE TABLE IF NOT EXISTS ai_usage (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  used_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_wedding ON ai_usage(wedding_id);

-- Events (wedding events / sub-events)
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  user_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  location TEXT,
  start_time TEXT,
  end_time TEXT,
  is_public INTEGER NOT NULL DEFAULT 1,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_events_wedding ON events(wedding_id);

-- Invitations
CREATE TABLE IF NOT EXISTS invitations (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  template_id TEXT,
  token TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  sent_at TEXT,
  opened_at TEXT,
  scheduled_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE INDEX IF NOT EXISTS idx_invitations_wedding ON invitations(wedding_id);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);

-- Invitation Templates
CREATE TABLE IF NOT EXISTS invitation_templates (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Messages (guest ↔ couple messaging)
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  content TEXT NOT NULL,
  sender_type TEXT NOT NULL DEFAULT 'guest',
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_messages_wedding ON messages(wedding_id);

-- Gift Registry
CREATE TABLE IF NOT EXISTS gift_registry (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price REAL,
  url TEXT,
  image_url TEXT,
  is_purchased INTEGER NOT NULL DEFAULT 0,
  purchased_by TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_gift_registry_wedding ON gift_registry(wedding_id);

-- Guest Photos
CREATE TABLE IF NOT EXISTS guest_photos (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  file_url TEXT NOT NULL,
  caption TEXT,
  is_approved INTEGER NOT NULL DEFAULT 0,
  uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

CREATE INDEX IF NOT EXISTS idx_guest_photos_wedding ON guest_photos(wedding_id);

-- Images (general wedding images)
CREATE TABLE IF NOT EXISTS images (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  filename TEXT NOT NULL,
  original_filename TEXT,
  file_url TEXT NOT NULL,
  mime_type TEXT,
  size INTEGER,
  category TEXT,
  is_public INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_images_wedding ON images(wedding_id);

-- Venues
CREATE TABLE IF NOT EXISTS venues (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  location TEXT,
  address TEXT,
  capacity INTEGER,
  price_per_day REAL,
  website TEXT,
  phone TEXT,
  email TEXT,
  images TEXT,
  amenities TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Venue Requests (couple ↔ venue enquiries)
CREATE TABLE IF NOT EXISTS venue_requests (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  wedding_id TEXT NOT NULL,
  user_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  message TEXT,
  response TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- Venue Offer Categories
CREATE TABLE IF NOT EXISTS venue_offer_categories (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Offers
CREATE TABLE IF NOT EXISTS venue_offers (
  id TEXT PRIMARY KEY,
  category_id TEXT NOT NULL,
  venue_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  price REAL,
  unit TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (category_id) REFERENCES venue_offer_categories(id),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Documents
CREATE TABLE IF NOT EXISTS venue_documents (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  filename TEXT NOT NULL,
  file_url TEXT NOT NULL,
  doc_type TEXT,
  content_text TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Venue Chat History (AI-assisted venue enquiries)
CREATE TABLE IF NOT EXISTS venue_chat_history (
  id TEXT PRIMARY KEY,
  venue_id TEXT NOT NULL,
  wedding_id TEXT,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (venue_id) REFERENCES venues(id)
);

-- Seating Tables
CREATE TABLE IF NOT EXISTS seating_tables (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 10,
  shape TEXT NOT NULL DEFAULT 'round',
  x REAL,
  y REAL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_seating_tables_wedding ON seating_tables(wedding_id);

-- Seat Assignments
CREATE TABLE IF NOT EXISTS seat_assignments (
  id TEXT PRIMARY KEY,
  table_id TEXT NOT NULL,
  wedding_id TEXT NOT NULL,
  guest_id TEXT,
  seat_number INTEGER,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (table_id) REFERENCES seating_tables(id),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

-- RSVP Reminders
CREATE TABLE IF NOT EXISTS rsvp_reminders (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  send_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  target_rsvp_status TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

-- Reminder Sent Records
CREATE TABLE IF NOT EXISTS reminder_sent (
  id TEXT PRIMARY KEY,
  reminder_id TEXT NOT NULL,
  guest_id TEXT NOT NULL,
  sent_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (reminder_id) REFERENCES rsvp_reminders(id),
  FOREIGN KEY (guest_id) REFERENCES guests(id)
);

-- Moodboards
CREATE TABLE IF NOT EXISTS moodboards (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  user_id TEXT,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Moodboard Elements
CREATE TABLE IF NOT EXISTS moodboard_elements (
  id TEXT PRIMARY KEY,
  moodboard_id TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT,
  x REAL,
  y REAL,
  width REAL,
  height REAL,
  rotation REAL DEFAULT 0,
  z_index INTEGER DEFAULT 0,
  properties TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (moodboard_id) REFERENCES moodboards(id)
);

-- Agenda Items (wedding day schedule)
CREATE TABLE IF NOT EXISTS agenda_items (
  id TEXT PRIMARY KEY,
  wedding_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  start_time TEXT NOT NULL,
  end_time TEXT,
  location TEXT,
  responsible_person TEXT,
  "order" INTEGER DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (wedding_id) REFERENCES weddings(id)
);

CREATE INDEX IF NOT EXISTS idx_agenda_items_wedding ON agenda_items(wedding_id);

-- User Subscriptions (token billing)
CREATE TABLE IF NOT EXISTS user_subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  plan TEXT NOT NULL DEFAULT 'free',
  balance_tokens INTEGER NOT NULL DEFAULT 0,
  total_purchased INTEGER NOT NULL DEFAULT 0,
  total_consumed INTEGER NOT NULL DEFAULT 0,
  stripe_subscription_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Token Usage
CREATE TABLE IF NOT EXISTS token_usage (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  action TEXT NOT NULL,
  tokens_consumed INTEGER NOT NULL DEFAULT 0,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Analytics: Page Views
CREATE TABLE IF NOT EXISTS page_views (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  path TEXT NOT NULL,
  referrer TEXT,
  user_agent TEXT,
  ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_page_views_wedding ON page_views(wedding_id);

-- Analytics: Visits (sessions)
CREATE TABLE IF NOT EXISTS visits (
  id TEXT PRIMARY KEY,
  wedding_id TEXT,
  guest_id TEXT,
  session_id TEXT,
  started_at TEXT NOT NULL DEFAULT (datetime('now')),
  ended_at TEXT,
  page_count INTEGER DEFAULT 1
);

-- Analytics: Security Events
CREATE TABLE IF NOT EXISTS security_events (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  user_id TEXT,
  details TEXT,
  severity TEXT NOT NULL DEFAULT 'low',
  ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Stripe webhook idempotency log (folded in from migration_v2.sql).
-- _seen_event() relies on this table; it must always exist.
CREATE TABLE IF NOT EXISTS stripe_events (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  processed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_type ON stripe_events(event_type);

-- Foreign-key indexes for hot lookups (F25).
CREATE INDEX IF NOT EXISTS idx_seat_assignments_table ON seat_assignments(table_id);
CREATE INDEX IF NOT EXISTS idx_seat_assignments_wedding ON seat_assignments(wedding_id);
CREATE INDEX IF NOT EXISTS idx_seat_assignments_guest ON seat_assignments(guest_id);
CREATE INDEX IF NOT EXISTS idx_venue_chat_history_venue_wedding ON venue_chat_history(venue_id, wedding_id);
CREATE INDEX IF NOT EXISTS idx_venue_requests_wedding ON venue_requests(wedding_id);
CREATE INDEX IF NOT EXISTS idx_venue_offer_categories_venue ON venue_offer_categories(venue_id);
CREATE INDEX IF NOT EXISTS idx_venue_offers_category ON venue_offers(category_id);
CREATE INDEX IF NOT EXISTS idx_venue_documents_venue ON venue_documents(venue_id);
CREATE INDEX IF NOT EXISTS idx_invitation_templates_wedding ON invitation_templates(wedding_id);
CREATE INDEX IF NOT EXISTS idx_moodboards_user ON moodboards(user_id);
CREATE INDEX IF NOT EXISTS idx_moodboard_elements_moodboard ON moodboard_elements(moodboard_id);
CREATE INDEX IF NOT EXISTS idx_token_usage_user ON token_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_reminder_sent_reminder ON reminder_sent(reminder_id);

-- =====================================================================
-- Wedding Website Builder (structured-content sites) — migration 004
-- =====================================================================
-- A wedding's public website is a structured JSON document of typed blocks,
-- validated by services/site_schema.py (the authoritative validator). No user-
-- or model-authored HTML is ever stored: themes render the typed blocks.
--
-- ID TYPES: every other table here uses TEXT uuid ids, and weddings.id /
-- guests.id are TEXT. These website tables use their own INTEGER rowid PK
-- (monotonic — relied on to prune revisions to the most recent 10), but each
-- FOREIGN KEY column keeps its referent's actual type:
--   wedding_id       -> weddings(id)       TEXT
--   matched_guest_id -> guests(id)         TEXT
--   site_id          -> wedding_sites(id)  INTEGER

CREATE TABLE IF NOT EXISTS wedding_sites (
  id INTEGER PRIMARY KEY,
  wedding_id TEXT NOT NULL UNIQUE REFERENCES weddings(id),
  slug TEXT NOT NULL UNIQUE,
  custom_host TEXT UNIQUE,                 -- reserved for the later wildcard-domain phase
  theme TEXT NOT NULL DEFAULT 'classic',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','unpublished')),
  draft_content TEXT NOT NULL DEFAULT '{}',
  published_snapshot TEXT,
  published_at TEXT,
  rsvp_enabled INTEGER NOT NULL DEFAULT 1,
  password_hash TEXT,                      -- optional guest password (PBKDF2 via the auth helper)
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_wedding_sites_slug ON wedding_sites(slug);
CREATE INDEX IF NOT EXISTS idx_wedding_sites_custom_host ON wedding_sites(custom_host);

-- Immutable published snapshots — one row inserted on every publish, then
-- pruned to the most recent 10 per site (ordered by the monotonic id).
CREATE TABLE IF NOT EXISTS site_revisions (
  id INTEGER PRIMARY KEY,
  site_id INTEGER NOT NULL REFERENCES wedding_sites(id),
  snapshot TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_site_revisions_site ON site_revisions(site_id);

-- Public website RSVP responses.
--
-- DISTINCT from the existing guest-token RSVP flow (guest_routes: one row per
-- invited guest, authenticated by guests.unique_token, writes guests.rsvp_status).
-- This is the OPEN public-website form: anyone may submit, there is no token,
-- and we best-effort fuzzy-match to an existing guest (matched_guest_id) without
-- requiring one.
CREATE TABLE IF NOT EXISTS site_rsvp_responses (
  id INTEGER PRIMARY KEY,
  wedding_id TEXT NOT NULL REFERENCES weddings(id),
  site_id INTEGER NOT NULL REFERENCES wedding_sites(id),
  guest_name TEXT NOT NULL,
  email TEXT,
  attending INTEGER NOT NULL,
  party_size INTEGER NOT NULL DEFAULT 1,
  dietary TEXT,
  message TEXT,
  matched_guest_id TEXT,                   -- best-effort fuzzy match to guests(id); may be NULL
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_site_rsvp_responses_wedding ON site_rsvp_responses(wedding_id);
CREATE INDEX IF NOT EXISTS idx_site_rsvp_responses_site ON site_rsvp_responses(site_id);
